### ISSUE TITLE
Re-order content modules

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#1039]
• Each paragraph of text should be treated as a separate 'block'
• When hovering on a block there should be a small icon in the upper left
• Grabbing this icon will allow you to move the block up or down (example of how I have seen that work here: https://cl.ly/443t3Q2D0e0H)

![Uploading Screen Shot 2017-05-18 at 1.33.57 PM.png…]()

**Comment by eessex** [comment]
@owendodd possible to add the image again?

**Comment by owendodd** [comment]
Whoops!

<img width="694" alt="screen shot 2017-05-18 at 6 29 04 pm" src="https://cloud.githubusercontent.com/assets/3196536/26213124/2a1c5970-3bf8-11e7-96fe-707934752ba9.png">

svg here:
[Combined Shape.svg.zip](https://github.com/artsy/positron/files/1011599/Combined.Shape.svg.zip)
