### ISSUE TITLE
Drag and drop within image pairs and image sets

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#1071]
- [x]  Ability to reorder images within and image paring (in an image section)
- [x]  Ability to reorder images within an image set

**Comment by eessex** [comment]
@owendodd, our section menu is now shorter - which layout do you prefer?
![screen shot 2017-06-22 at 2 03 04 pm](https://user-images.githubusercontent.com/1497424/27448717-c8fc5ba0-5753-11e7-8389-c445e33ba2c3.png)
![screen shot 2017-06-22 at 2 04 05 pm](https://user-images.githubusercontent.com/1497424/27448718-c8fd68e2-5753-11e7-8ecc-97c39a13951f.png)

**Comment by owendodd** [comment]
@eessex Lets do the single line!
