### ISSUE TITLE
An admin can create a Writer user

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#108]
![image](https://cloud.githubusercontent.com/assets/555859/6159646/541390b2-b226-11e4-8a24-4bfd09978cce.png)

**Comment by halleyjohnson** [comment]
@craigspaeth Do we have an ETA for this, or is there a way you can just allow my account to do this (or Artsy Editorial's, if you're comfortable with that)? We are creating profiles for 3-5 insiders per fair to post their picks, and don't want to overload you with requests for user accounts.

**Comment by craigspaeth** [comment]
I'll work on it next, probably a couple days of work though so maybe mid next week?

**Comment by halleyjohnson** [comment]
Cool. In the meantime I'll just send you the most pressing ones.
