### ISSUE TITLE
Custom Joi extension for ObjectId

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#1086]
Joi has had the ability to create [custom extensions](https://github.com/hapijs/joi/blob/v10.0.1/API.md#extendextension) for a while now. We should use this for ObjectId validation.

Original suggestion here: https://github.com/artsy/positron/pull/847#discussion_r89937098

**Comment by eessex** [comment]
Ooh cool, maybe this could be helpful for our section validation -- have been trying to get better messages for validated values nested in objects, but Joi seems to stop at the top level.  Specifically wanted to implement this for required caption fields.
