### ISSUE TITLE
Auto-link mentions of artist names in text

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#1100]
@halleyjohnson's 7pm product improvement idea:

Currently interns spend a lot of time creating links for artist mentions within the body of an article. This is kind of like the opposite of "feature mentioned".

Given a text that looks like:

> “People are in the mood to buy,” said Eleanor Acquavella, as the ink dried on a sale of Jean-Michel Basquiat's Three Delegates (1982) for between $15 million and $20 million.

Recognize artist names and convert them to links:

> “People are in the mood to buy,” said Eleanor Acquavella, as the ink dried on a sale of [Jean-Michel Basquiat](https://artsy.net/artist/jean-michel-basquiat)'s Three Delegates (1982) for between $15 million and $20 million.

Still unclear as to how the checker would work given artist name variations and if this would actually work as you type or maybe as a button called "Click to Auto-Link Artists".

**Comment by eessex** [comment]
Yeah this sounds doable -- we are already collecting mentioned artists for the 'featured' admin section, could run a check for name matches on save.
