### ISSUE TITLE
Better solution for Icons

### ISSUE THREAD

**Issue by eessex** [artsy/positron#1102]
Each section in the edit app has its own 'icons' jade file -- these should be consolidated in a single file, or we should find a better solution for rendering them.

**Comment by kanaabe** [comment]
@eessex shall we close this now that we have a master icons.jade file?

**Comment by eessex** [comment]
Another option would be to keep these in our npm package -- added one for the imageset, but isn't exported ATM. This we could easily add the ability to give colors etc as props. 
https://github.com/eessex/particle2/blob/b1cac19788e1448d0bbb131551ceae32b5e6f691/src/icons/imageset.jsx
