### ISSUE TITLE
Article Types Overview

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#1117]
Here is a breakdown of the toolsets for the initial two article types, features and standard. Starred items are new and will have more detailed issues explaining them.

## Feature Articles:
**Header** ([Issue Here](https://github.com/artsy/publishing/issues/18))
- Full screen image header
- Split screen image header*
- Text header with full width image*

**Images** ([Issue Here](https://github.com/artsy/positron/issues/1120))
- Full screen images* 
- Full width image(s)
- Body width images
- Image sets

**Text** ([Issue Here](https://github.com/artsy/positron/issues/1121) and [here](https://github.com/artsy/positron/issues/1122))
- H2, H3, Bold, Italic
- Links, artist links
- Section Headers*
- Pull Quotes*
- Section Breaks*
- Drop Caps*

**Other**
- Video 
- Embed

## Standard Articles (Issue Here)
**Header** 
(No header options)
- Plain text header (as is)

**Images**
(No full screen images)
- Full width image(s)
- Body width images
- Image sets

**Text** ([Issue Here](https://github.com/artsy/positron/issues/1121))
(No drop caps, some alt styles)
- H2, H3, Bold, Italic
- Links, artist links
- Section Headers* (different styling)
- Pull Quotes* (different styling)
- Section Breaks*

**Other**
- Video 
- Embed

## Depreciated Tools
- TOC
- Callouts

**Comment by eessex** [comment]
Currently the image collection allows an unlimited number of images, not just pairs -- although this seems to be the most regular use.  Is there a reason we need to limit this?  In the forthcoming changes to images you can toggle between imageset and image collection, so switching from a set of many images to a collection with a limit of 2 may be an issue.

**Comment by owendodd** [comment]
No that isn't an issue, just me mis-remembering the feature

-- 
Owen Dodd

**Comment by kanaabe** [comment]
This is awesome @owendodd. A few questions -- 

1. Assuming Top Stories is also deprecated 🥊 
2. How does this feature list change for partners/non-editorial channels?
3. Related to partners, will their front-ends also be updated? We might be able to temporarily keep the old formatting for partners/fair embedding since layout rendering is siloed into a component in Force. Basically, we can start by only changing artsy.net/article/:slug since we separate the layout rendering from the sub-app itself.

**Comment by owendodd** [comment]
@kanaabe 
Yes to depreciating top stories 😏 .

As for partners, the front end for those articles won't change. I think it makes more sense to just keep those as is. Same is true for the feature set. Maybe what we have now becomes another article type that is only available to non-ed. Would that work?
