### ISSUE TITLE
Postscripts/corrections field?

### ISSUE THREAD

**Issue by eessex** [artsy/positron#1211]
For feature articles we are designating the end of the body text with a black dot. Possible edge case is italic text that sometimes follows articles as correction, credits or a postscript.
Do we want to add a field for this after the end of the article body?

![screen shot 2017-08-01 at 1 30 49 pm](https://user-images.githubusercontent.com/1497424/28838210-ada0107a-76bd-11e7-8e13-f0627771ba2b.png)

**Comment by eessex** [comment]
cc @owendodd

**Comment by owendodd** [comment]
Definitely seems worth it. 

![screen shot 2017-08-01 at 3 06 08 pm](https://user-images.githubusercontent.com/3196536/28842276-0265d06a-76cb-11e7-926e-a28f0a3c2c92.png)

**Comment by eessex** [comment]
Cool, got any thoughts on a placeholder name for this field?

**Comment by owendodd** [comment]
@eessex Maybe 'Footnote' or 'Appendix'?

**Comment by owendodd** [comment]
Eh, actually I think maybe just 'Postscript' is good
