### ISSUE TITLE
Article Layouts Reflected in Writer

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#1214]
Content:
- [x] Hero section
- [x] Header
- [x] Image Collection
    - [x] Can toggle image_set layout
    - [x] Center aligns images if less than container size
- [x] Video
- [x] Postscript
- [ ] Author preview
- [x] Embed
- [x] Text

Admin: 
- [x] New author field
- [x] Toggle article layout

Misc:
- [x] Choose layout menu
- [x] Superarticles ??

**Comment by eessex** [comment]
Content:
- [ ] Hero section
- [ ] Header
- [ ] Text
- [ ] Image Collection
- [ ] Video
- [ ] Embed
- [ ] Postscript
- [ ] Author preview

**Comment by eessex** [comment]
- [ ] superarticles
