### ISSUE TITLE
Icons for Article2 features

### ISSUE THREAD

**Issue by eessex** [artsy/positron#1243]
- [x] Feature header for toggling layouts
- [x] Image collection fullscreen layout
- [x] Image Set full and mini

**Comment by owendodd** [comment]
Feature Header Toggle
SVGs: https://cl.ly/250B002g1F0e
Sketch: https://zpl.io/VDkG332

**Comment by owendodd** [comment]
For Image set entry points lets do a little toggle like this: 

![screen shot 2017-08-30 at 2 28 05 pm](https://user-images.githubusercontent.com/3196536/29888716-dd081c5c-8d8f-11e7-8d7f-e9fd87e76d26.png)

**Comment by owendodd** [comment]
Image Collection Fullscreen: https://cl.ly/0I01392b0x1Y

(its just a 38 x 22px rectangle)

**Comment by eessex** [comment]
I find the language for the image-set a little confusing -- mostly in that i don't really see the small version as a button.  What do you think of using 'full' and 'mini', like we have in the API?

**Comment by owendodd** [comment]
Full / Mini works for me! Thanks eve
