### ISSUE TITLE
Can't highlight all on text section with mouse click

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#1260]
Reproduction steps:
1. Create a text section
2. Triple click in text section
3. All text is not highlighted

Note, command + a works fine

Chrome, latest

**Comment by owendodd** [comment]
This still isn't really working for me: https://cl.ly/3a0O0h0P2t3J

Not seeing anything highlighted

**Comment by eessex** [comment]
@owendodd what browser is this video in?  works well for me in chrome.

**Comment by owendodd** [comment]
Chrome for me too

**Comment by owendodd** [comment]
trying again

**Comment by owendodd** [comment]
Seems to be specific to feature articles for me
