### ISSUE TITLE
Add Yoast panel to Team Channels

### ISSUE THREAD

**Issue by eessex** [artsy/positron#1268]
Requested by Nicolette https://artsy.slack.com/archives/C04GGGDCM/p1504816073000158

**Comment by NicoletteChao** [comment]
Hi @eessex just checking in to see if there's an anticipated timeline I can share with my team! There are a couple of marketing teams that are writing content that this would be useful for

**Comment by eessex** [comment]
@NicoletteChao, we are adding the feature this week -- however, it will be added to our redesigned editor, which is being deployed at the end of October.  Is this ok for your timeline?

**Comment by NicoletteChao** [comment]
@eessex that works for us, thanks for the update!
