### ISSUE TITLE
Writer Article QA

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#1284]
- [x] Need a UI for adding related articles (formerly callouts)

- [x] Weird caption styling https://cl.ly/1n3N0K0x3b1R
- [ ] Image error https://cl.ly/2M1t39111h1X
- [x] Paragraphs are only sometimes split into sections https://cl.ly/373u0x2X0U2P
- [ ] Images not filling width https://cl.ly/2W3i2P1d0z33

General
- [x] Caption should not allow linebreaks
- [ ] Yoast works with new layouts
- [ ] Empty field indicators work with new layouts
- [x] Section tool should not hover when editing a section

Image collection
- [x] Content should justify center if it is narrower than container
- [ ] Bug of captions not moving on drag/drop is back
- [ ] File upload limit is 30MB, should we bump down to 10?
- [x] Image set layout can be changed

Video
- [ ] Error message for required captions

Postscript
- [x] Cursor doesn't line up with placeholder

Text
- [ ] Decorated line break (with dot)

**Comment by eessex** [comment]
FYI paragraphs are only split into sections when you hit enter twice.  This will facilitate the line-break dot when that feature is added.

**Comment by owendodd** [comment]
Ah right right, sorry!

**Comment by eessex** [comment]
@owendodd, currently we are limiting image height at 70vh, and aligning them to the center if it doesn't fill the container.  Since the containers are narrower now, do you want to remove this restriction, or keep in place?

**Comment by owendodd** [comment]
@eessex We can get rid of that limitation

**Comment by craigspaeth** [comment]
@eessex is to wrap up open branch and icebox this ticket which we'll break up next sprint (post 30th).
