### ISSUE TITLE
Check if tracking tags are being sent to Looker

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#1313]
Tracking tags aren't showing up under articles as an option in Looker, and they're not being grouped into the "Tags" field—looks like that one is just topic tags.

**Comment by kanaabe** [comment]
@halleyjohnson I confirmed that we're sending the tracking_tags on our end! https://github.com/artsy/positron/blob/master/scripts/daily_upload_s3.coffee#L108
