### ISSUE TITLE
A lot of issues with saving formatting made in Writer

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#133]
Basically impossible to format text within the Writer platform and have it save to draft or sync to the site. Rather have to create formatting text elsewhere and paste it in to get it to stick.

This has been a big problem with formatting old posts in Writer—have had to delete several entirely and republish from within Writer to get changes to stick.

**Comment by halleyjohnson** [comment]
Hey @craigspaeth just reiterating that this is a big working issue with Writer, and one we should fix before extending it to partners—I think even though it can be jogged with some patience/trying different methods, these are the kind of issues that overwhelm users and frustrate them into thinking it's completely unfunctional... if feedback from other team members using Writer is any indication.

**Comment by craigspaeth** [comment]
@halleyjohnson: Can you try to reproduce some of these issue and list out the steps. I'll start one for example:

1. Start a new article
2. Paste in some text e.g. "Hello World"
3. Highlight a word e.g. "World"
4. Click on the bold icon and it doesn't bold the world it just jumps the cursor to the left.

After logging enough of ^ these things will smooth out but right now it's difficult to do the detective work.

**Comment by craigspaeth** [comment]
I think a lot of this was smoothed over with my latest deploy of bug fixes. Please log new related issues as you see them (keeping in mind the steps to reproduce I gave an example of above).
