### ISSUE TITLE
[Gucci] Analytics Tracking

### ISSUE THREAD

**Issue by eessex** [artsy/positron#1416]
- [x] Video play
- [ ] Share buttons
- [x] Click partner logo
- [x] External links in footer copy
Need to double check with analytics team for tracking event info

**Comment by eessex** [comment]
@wrgoldstein can you confirm how we should label events for the Gucci partnership? I'm assuming you want the page title or slug included -- below is an example of what  I've set up so far. 

`{
  action: "Click",
  label: "Play video",
  entity_type: "article",
}`

**Comment by wrgoldstein** [comment]
Yep that's perfect. We get the page url from the tracking library for free (which includes the slug), so if we just add in the article id as `entity_id` we'll be able to connect it back to the positron articles table.

**Comment by wrgoldstein** [comment]
Sorry I thought this was an article, if it isn't, can I get a link to the page?

**Comment by eessex** [comment]
@wrgoldstein this is actually not an article (it is a curation) -- so we'd need to treat it as a 1-off more like the venice project.  I can pass the id but it won't map to articles.

**Comment by eessex** [comment]
Here is the project, requires being logged in: https://staging.artsy.net/gender-equality

**Comment by wrgoldstein** [comment]
Okay then let's scrap the `entity_type: 'article'` bit from above.  How about

```
analytics.track("Click", {type: "play video", label: "<specific video content title>")
```

And let's not forget to also instrument any links out to Gucci if they exist.

**Comment by eessex** [comment]
Cool thanks, what label should we use for partner links?

**Comment by wrgoldstein** [comment]
```
analytics.track("Click", {type: "external link", destination_path: "www.gucci.com"})
```
would be perfect

**Comment by eessex** [comment]
@wrgoldstein,  this project is launching in about an hour -- can you confirm these tracking calls are correct?
We are not passing any info that links these all back to the same source url, should we be passing a label like `"Gucci Gender Equality"` or the source slug: `/gender-equality`?

External link/partner logos:
![screen shot 2017-11-13 at 10 25 20 am](https://user-images.githubusercontent.com/1497424/32733441-43248964-c85d-11e7-8829-b9ed952cdb91.png)

Video:
![screen shot 2017-11-13 at 10 29 05 am](https://user-images.githubusercontent.com/1497424/32733546-8ab98e1e-c85d-11e7-904e-99102fc0397c.png)

Share:
![screen shot 2017-11-13 at 10 32 37 am](https://user-images.githubusercontent.com/1497424/32733694-0479ec30-c85e-11e7-8f31-3d7836f1e332.png)

**Comment by wrgoldstein** [comment]
For consistency let's do:
```
// external link
analytics.track("Click", { type: "external link", destination_path: partner_url })

// video
analytics.track("Click", { type: "play video", label: section.featuring })

// share
analytics.track("Click", { type: "share", label: service })
```

Re: your question, according to [the spec for analytics.js](https://segment.com/docs/spec/track/) you don't need to pass the url explicitly.

**Comment by eessex** [comment]
Perfect, thanks @wrgoldstein
