### ISSUE TITLE
mix of staff writer & non-staff writer feels funky at the bottom of an article

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#1462]
Due to our bio/photo conventions, which I can share directly @owendodd , this article written by a staff member & a non-staff member felt v weird when I published (I removed their bylines from admin and put them in text for now).

<img width="812" alt="screen shot 2017-12-03 at 2 52 51 pm" src="https://user-images.githubusercontent.com/10982707/33529270-a06cfda6-d83c-11e7-88b9-bf8793e6f4ee.png">

https://www.artsy.net/article/artsy-editorial-18-new-dealers-watch-art-basel-miami-beach

**Comment by owendodd** [comment]
moving to publishing repo https://github.com/artsy/publishing/issues/289
