### ISSUE TITLE
Preview button for partners includes partner slug

### ISSUE THREAD

**Issue by eessex** [artsy/positron#1475]
Preview button goes to /article for partners, which gives a 403

**Comment by kanaabe** [comment]
Force is set up to redirect to the partner page if it detects one. For example, https://writer.artsy.net/articles/58d535ba8fcf0a002767b338/edit works. Is it possible that the article you looked at did not have a partner association?

**Comment by eessex** [comment]
This is the article where the error was seen, it does have a partner association.
