### ISSUE TITLE
Bug fixes to upgrade to React 16

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#1519]
@eessex brought this up and we discussed in person, but there's an additional issue with upgrading to 16 where we sometimes clone a prop incorrectly which causes the component to break.

Example:
https://github.com/artsy/positron/blob/8894c4d5ad80fc9eafd6e9f53c48a5b0dcd2085f/client/components/drag_drop/index.coffee#L46

Right now, 16 is merged into master but rolled back from Production. This is currently blocking deploys. I don't feel too strongly about the blocked deploys since we're not working on a deadline ATM. @eessex is going to give an estimate and we'll make a decision from there. It seems like we should revert it anyway, but I'll let @eessex make the call!

This would also be a good time to ensure we have tests that will cover these cases in the future.

**Comment by damassi** [comment]
@eessex - did the React 16 stuff ever get shipped? Is this still an open issue?
