### ISSUE TITLE
Captions in slideshow not sticking to their correct image 

### ISSUE THREAD

**Issue by sarahdotson** [artsy/positron#1575]
If I add a slideshow in Writer, then try to move around the images/change the order, the captions for the image do not move with it, and instead stay in the same place. I'm attaching screenshots of a slideshow where I move the images into different orders, but as you can see the caption does not move with the image.

<img width="1151" alt="screen shot 2018-02-08 at 11 30 08 am" src="https://user-images.githubusercontent.com/31517643/35984999-9c479054-0cc3-11e8-9b50-c0e5a91c229a.png">

<img width="983" alt="screen shot 2018-02-08 at 11 30 18 am" src="https://user-images.githubusercontent.com/31517643/35985006-9ef6e7aa-0cc3-11e8-9ca9-f07e9cb947ee.png">

<img width="912" alt="screen shot 2018-02-08 at 11 30 24 am" src="https://user-images.githubusercontent.com/31517643/35985011-a1285040-0cc3-11e8-9be9-16b1b1ab6cee.png">

**Comment by eessex** [comment]
@sarahdotson Yeah this is a known bug -- if you close the section and re-open it should render the captions in the correct place after drag-n-drop.  Hoping this bug will be killed in the redux changes coming up.
