### ISSUE TITLE
Title not saving in drafts unless you also add in Display

### ISSUE THREAD

**Issue by sarahdotson** [artsy/positron#1576]
If you make a draft and add a title, it won't save the title and will appear in the drafts page as "Missing Title." You have to go and add it in the display panel under the "Magazine Headline" if you want the title to appear in the drafts page. 

I added this:
<img width="819" alt="screen shot 2018-02-08 at 11 42 55 am" src="https://user-images.githubusercontent.com/31517643/35985943-c8ea28e0-0cc5-11e8-8738-46beceacc9db.png">

And this is what it looks like in the draft page if you don't also put it in the Magazine Headline field:
<img width="563" alt="screen shot 2018-02-08 at 11 43 08 am" src="https://user-images.githubusercontent.com/31517643/35985959-d4fa4a84-0cc5-11e8-97f7-09e3012f4f9d.png">

**Comment by eessex** [comment]
@sarahdotson this is technically not a bug -- the list view is built to show the magazine headline rather than the article title.  I believe this might be as an additional indicator that the field is not completed. Perhaps there is a way to change the UI so this is more obvious, cc @owendodd
