### ISSUE TITLE
"Organizations" e.g. Artsy Editorial = Organization, Tess = User

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#168]
for linking articles to their authors, for example an Artsy Editorial piece Halley wrote gets reposted to her personal profile but lives on Editorial's profile. currently doing this via old admin

**Comment by craigspaeth** [comment]
@halleyjohnson: I've thought it over and I'd like it if we held off on blindly porting this functionality over from the old posting system. At-least for the immediate term I would like to not make this a blocker for launching Writer/Magazine.

In the past we had a more social posting platform and the idea of a "repost" (kinda like a fancier form of "Like"ing) a la Tumblr made sense. Now the primary use case, as you explain, is to indicate that someone is a part of a "Artsy Editorial" or is writing on behalf of "Artsy staff". I don't think the concept of "reposting" fits this well.

I don't know the right answer yet, but as an example, what Medium does would be more appropriate. Medium essentially has two concepts: "Users" (or authors) and what I'm going to call "Organizations"

e.g.

User: https://medium.com/@mwichary
Organization: https://medium.com/designing-medium

As you can see on a user's profile it will either show the article by their name

![image](https://cloud.githubusercontent.com/assets/555859/6587762/de7eb6a8-c75e-11e4-9cce-cac7c956e2fb.png)

or by the organization name + the author name

![image](https://cloud.githubusercontent.com/assets/555859/6587773/f8bb0fe4-c75e-11e4-9249-a6595d767c6d.png)

I could imagine Artsy adopting a similar data model. Or maybe something as simple as a checkbox indicating this article was written by staff. Either way I don't think we should be able to post things on other user's profiles, nor should we be porting "reposting" functionality now that we're aiming for a less social-network-like editorial platform.

**Comment by halleyjohnson** [comment]
@craigspaeth As mentioned, this sounds great to me. If you're comfortable enough with using that Medium format, I can run this by Editorial at standup this afternoon and get some general feedback?

**Comment by halleyjohnson** [comment]
I think this can also solve our author issue on the landing page, right? So you'd get both "Artsy Editorial" and the writer's name on Magazine?

**Comment by craigspaeth** [comment]
@halleyjohnson That's the general idea, but that level of detail I still need to work out with Robert.

**Comment by craigspaeth** [comment]
Another big win of this is Facebook author tags http://seekingalpha.com/article/3277825-facebook-author-tags-a-rising-tide-for-content-content-marketing-growthhacking-players?auth_param=dudr8:1aoisu0:bc63797816f877715e451fcbf45666e2&uprof=25

Dig up an email with title "Fwd: FB: Facebook: Author Tags A Rising Tide For Content, Content Marketing, Growthhacking Players" for more notes.

**Comment by craigspaeth** [comment]
Initial thoughts about the data model...

db.organizations
````
{
  name: 'Artsy Editorial',
  icon_url: 'http://foobar.com/foo.jpg',
  user_ids: [ObjectId('...')],
  ... TBD after design review maybe "banner_url", "slogan", "twitter_handle", etc
}
````

Following might not even be necessary for an MVP, but here:
````
db.organization_followers
{
  user_id: ObjectId('...'),
  organization_id: ObjectId('...')
}
````

**Comment by craigspaeth** [comment]
For starters we can start with just `icon_url` and `name`. Use verticals as a reference for implementation as it will be the same gist—expose GETs via API, protect PUT/POST/DELTES to admin only and add an admin-only UI in the sidebar like Verticals... sidebar icon TBD—feel free to use the verticals icon in the meantime.

![organization](https://cloud.githubusercontent.com/assets/555859/8488266/665a0620-20df-11e5-9870-1badfa38ffff.png)

**Comment by craigspaeth** [comment]
@broskoski & @kanaabe Feel free to pair on this, bounce it back my way, or just one of you take the reins completely. See my last comment for the first step MVP to make this happen at a data-level... I realize I forgot about associating users to the organization in my comp, but I'll follow up with an issue for that as a second step.
