### ISSUE TITLE
set "what to read next" section to tier 1 articles only [ASAP, interim period only]

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#170]
so we don't give inadvertent access to /article form of every post on the site before launch
![screen shot 2015-03-03 at 11 22 40](https://cloud.githubusercontent.com/assets/10982707/6466730/b7423bea-c197-11e4-8d6e-40c04e63c2c9.png)

**Comment by craigspaeth** [comment]
:+1: for the [array](http://www.wikiwand.com/en/Array) syntax @halleyjohnson.

````ruby
conditions = ['ASAP', 'interim period only']
````

**Comment by halleyjohnson** [comment]
@craigspaeth like I know what I'm doing
