### ISSUE TITLE
error message after saving draft

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#173]
unable to return to drafts page (not sure of particular trigger, have been working for a while in Writer and then hit save draft, this has come up before)

![screen shot 2015-03-04 at 14 19 51](https://cloud.githubusercontent.com/assets/10982707/6491195/ab28a0d2-c279-11e4-96af-6bd54ce0cbee.png)

**Comment by craigspaeth** [comment]
Weird. I've seen that before too but only locally. Are you able to get past this page, or is that still happening to you.

**Comment by halleyjohnson** [comment]
Still happening. I’m working in incognito to get around, can’t remember how I fixed this before. Probably just waited?

—
Halley Johnson
Editorial Associate

Artsy  ⁄  401 Broadway, 25th Floor, New York, NY, 10013

halley@artsy.net
Artsy Editorial 

On 4 March 2015 at 14:25:44, Craig Spaeth (notifications@github.com) wrote:

Weird. I've seen that before too but only locally. Are you able to get past this page, or is that still happening to you.

**Comment by craigspaeth** [comment]
Ok that's definitely very helpful. You can probably fix this by clearing cookies.

**Comment by halleyjohnson** [comment]
Noting, cookies cleaned this in short term.

**Comment by craigspaeth** [comment]
I'm going to take this out of the milestone until we can discover steps to reproduce... tricky to determine what's happened there.
