### ISSUE TITLE
too many uploaded images causes major rendering issues

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#184]
when you upload too many images (I've seen this issue with as few as four-five, but when you do 11 like I did last week it is horrendous), Writer starts displaying them all as the same, duplicating them, and many other bad rendering things. It maintains the images where you left them but you have to work from memory to make everything sync right... I can resimulate this for you if it helps!

**Comment by craigspaeth** [comment]
This should be fixed now. Lemme know if you see anything that's still an problem regarding this.
