### ISSUE TITLE
Writer Preview is crazy

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#189]
When you hit "preview" on a draft you rarely see the post you're working on, but rather some old post that's unclearly related (could be a duplicate URL issue, ie. if you've made a post called "draft" before and work under a new draft titled the same thing, the working URL for the posts would be the same) but the case below is definitely not the same URL (maybe it was when I first created it? I don't think so, though).

This would help a lot with mocking up posts, since sometimes we're posting things as drafts to see how they look now and that's screwing with URLs/SEO.

Draft in my Writer currently:
![screen shot 2015-03-10 at 10 56 53](https://cloud.githubusercontent.com/assets/10982707/6577432/4bc8ce24-c714-11e4-9f2b-9a62f931176c.png)

When I hit Preview:
![screen shot 2015-03-10 at 10 57 05](https://cloud.githubusercontent.com/assets/10982707/6577437/548d7ce4-c714-11e4-9d34-6fc818cb68b0.png)

**Comment by craigspaeth** [comment]
@halleyjohnson: I've got a fix coming for the preview thing not working. I've logged the URL issue separately, could you leave any extra thoughts regarding slugs here: https://github.com/artsy/positron/issues/194?

**Comment by halleyjohnson** [comment]
@craigspaeth Just noting this is still buggy:
![screen shot 2015-03-30 at 14 50 56](https://cloud.githubusercontent.com/assets/10982707/6904054/7433690e-d6ec-11e4-8443-f4e88cafb339.png)

![screen shot 2015-03-30 at 14 51 05](https://cloud.githubusercontent.com/assets/10982707/6904056/77eb40b2-d6ec-11e4-904f-abfc7a5bbac0.png)

**Comment by craigspaeth** [comment]
@halleyjohnson: There's two issues here, correct me if I'm wrong:

1. Right now you can't preview a draft it just 404s for me https://github.com/artsy/positron/issues/309
2. Articles with the same title by the same author are problematic. This is an issue with slugs not being unique... we can either A. Use ids + slugs e.g. /article//41ef1432f2/sabrina-buell-my-highlights-from-fog-design-plus-art-2015 like [Quartz does](http://qz.com/373228/hosting-the-winter-olympics-in-beijing-is-a-terrible-idea/) or B. Try to be a little more unique with the slug like adding last saved date/time to it e.g. /article/sabrina-buell-my-highlights-from-fog-design-plus-art-2015-03-30-2015 logged: https://github.com/artsy/positron/issues/310

Closing in favor of the two stories, please leave thoughts on #2 here https://github.com/artsy/positron/issues/310
