### ISSUE TITLE
images not displaying in migrated article format for old posts / article URLs not updating unless they've been opened in Writer

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#191]
Getting a weird sampling of results when I try to view article format for old posts (ie. not drafted in Writer). Mostly no images are showing up at all:
https://www.artsy.net/article/546ce9eb726169430ad30100
https://www.artsy.net/article/53c523887261693f70c41900

In this one, only one is displaying:
https://www.artsy.net/article/546cc55472616943d1670000

This is regardless of whether the post has been opened in Writer—I just opened this one in Writer (the images loaded there), hit "save article" and nothing showed up. https://www.artsy.net/article/artsy-editorial-john-alexander-s-early-abstractions-foreshadow-a-lifetime

Also, to note: you can see that the first three links have generic URLs not related to the post URLs they correspond to. However, the last link (john alexander) updated when I opened the post in Writer, then resaved. (The original generic URL now redirects to the fancy one.)

**Comment by craigspaeth** [comment]
Missing images will be solved with https://github.com/artsy/force/issues/2176 and weird urls are fixed with: https://github.com/artsy/positron/pull/187 I just need to re-run the migration script.
