### ISSUE TITLE
images no longer hosted an issue?

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#192]
Our posts preserve images even if the artworks they're linked to have been removed from the site. Here's an example: https://www.artsy.net/post/editorial-stray-dogs-and-city-streets-inspire-lena

Will these images be preserved in migration to Writer? We won't be able to re-add them to the posts, since they're not on the site as artworks anymore.

**Comment by craigspaeth** [comment]
@halleyjohnson Unfortunately I don't think so, we're just going to have to hide those missing works, related issue https://github.com/artsy/force/issues/2176.

FWIW I would think we'd want to keep artworks off the site (whether in an article or not) if a partner deletes or un-publishes it. But maybe I'm missing some kind of agreement we've made with partners saying we'll keep their images in articles no matter what the publish/deleted status is?
