### ISSUE TITLE
sometimes Writer gets tired

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#193]
After using Writer for some time and switching back and forth between multiple accounts (note this is how I use it all the time, so I can't say whether this issue crops up if you only use it in one account), things kind of break down—drafts don't save, buttons don't work, yesterday Molly couldn't get Writer to accept pasted copy—until you hit "sign out" (which you know only takes you back to your original account right now). Then it sort of wakes up again and is fine.

Actually remembering that didn't solve Molly's copy/paste problem, but opening an incognito window and logging in there did. That may be related to you working on the google docs thing yesterday, though?

**Comment by craigspaeth** [comment]
Hmm unfortunately it's hard to decipher action items to take out of this. Could you please try to reproduce these bugs individually and log them as separate bugs with steps to reproduce?

Going to close this in favor of those more granular issues.
