### ISSUE TITLE
Implement intercom.io

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#197]

**Comment by craigspaeth** [comment]
Should look like what CMS has with a black question mark in a cirlce in the bottom right corner.

**Comment by dylanfareed** [comment]
This is interesting. Maybe we should do a liaison onboarding in Writer and just use exactly the same intercom account as CMS.

**Comment by craigspaeth** [comment]
@dylanfareed :+1: I'm planning to do a Writer workshop with Insitutions/Liasons in the near future. I'll sync up with you on implementing the same intercom account when I get close to that. :beers:
