### ISSUE TITLE
Side nav shows broken image for users with no profile picture

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#212]
![image](https://cloud.githubusercontent.com/assets/2236794/6632741/eb681b5c-c911-11e4-9999-bc7b30044f66.png)

**Comment by halleyjohnson** [comment]
@kanaabe My profile image is broken, does that mean my admin profile image hasn't migrated to Writer?

**Comment by kanaabe** [comment]
@halleyjohnson i don't know that the two are related yet. I thought it was just pulling in the profile image from your Artsy profile but it looks like it might be something else. I'll have to do some digging!

**Comment by craigspaeth** [comment]
@kanaabe: I'm going to just patch this with a `$('img').on 'error', -> $('img').replace "placeholder.jpg"`. Down the line I have larger user refactors I would like to tackle that might involve using API v1 which has less issues with image urls.

**Comment by kanaabe** [comment]
Ok sounds good.

**Comment by kanaabe** [comment]
It looks like it's still happening - only on production. Strangely, my profile image works on staging

Production looks the same as above
On staging:
![2015-03-18_1653](https://cloud.githubusercontent.com/assets/2236794/6719187/550303ac-cd8f-11e4-8962-af64436bb6a8.png)

**Comment by craigspaeth** [comment]
@kanaabe: I think we just need to deploy Positron. Feel free to do so :)

**Comment by halleyjohnson** [comment]
@kanaabe @craigspaeth +1

On 18 March 2015 at 16:56:18, Craig Spaeth (notifications@github.com) wrote:

@kanaabe: I think we just need to deploy Positron. Feel free to do so :)

**Comment by kanaabe** [comment]
Ha, of course. Deployed.
