### ISSUE TITLE
Associate Articles with Auction Pages

### ISSUE THREAD

**Issue by katarinabatina** [artsy/positron#215]
Related to https://github.com/artsy/force/issues/2180

cc @dzucconi

**Comment by craigspaeth** [comment]
We can just add another admin autocomplete-select like fairs and partners

![image](https://cloud.githubusercontent.com/assets/555859/6789043/d4dd0194-d173-11e4-902a-adebb5c7e51d.png)

Down the line maybe we can consider having Ohm/Waves hook into the Writer API to centralize the "fair/auction" building experience.

**Comment by craigspaeth** [comment]
@kanaabe: You will also need to support this on the Writer API level which should be as simple as adding a Joi validation param [here](https://github.com/artsy/positron/blob/master/api/apps/articles/model.coffee#L66) and [here](https://github.com/artsy/positron/blob/master/api/apps/articles/model.coffee#L79).
