### ISSUE TITLE
Unable to edit article in writer

### ISSUE THREAD

**Issue by mollygottschalk** [artsy/positron#216]
I'm experiencing an issue where I'm unable to add new items to an article in writer.

When I got to add a new item (text or an artwork, for example) I hover my cursor over the place where I want the plus sign to appear. When I click the plus sign, the drop down menu shows up and then I choose, say, "text." However, at that point, the text box that already exists below pops up, giving me the option to edit the existing text, rather than add new text in a new text box. 

I have tried logging in and out, and working in an incognito window, but have not had any luck in solving the issue.

**Comment by mollygottschalk** [comment]
@craigspaeth

**Comment by craigspaeth** [comment]
Thanks @mollygottschalk. I think I've actually seen this before too, can you paste a screenshot of what it looks like when it focuses on the text section that already exists.

**Comment by mollygottschalk** [comment]
https://writer.artsy.net/articles/5506e5febea07e060091c0ea/edit
![screen shot 2015-03-16 at 4 07 54 pm](https://cloud.githubusercontent.com/assets/3266511/6675421/a6321816-cbf6-11e4-8253-abb5674615aa.png)

**Comment by mollygottschalk** [comment]
@craigspaeth
