### ISSUE TITLE
Indeterminate editing issues

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#221]
Had strange syncing issues with a couple of articles in the last two days. Currently working on this post: https://www.artsy.net/article/artsy-editorial-the-top-10-chinese-artists-not-named-ai (in top of Editorial's Writer account) and artworks are not showing up the same in Writer and on the live page. Either they're not appearing in Writer but show up on the front end (like the first module here) or they are not appearing at all (like the second). Yesterday had similar issues with this post: https://www.artsy.net/article/editorial-a-supercharged-art-dubai-becomes-the-hotbed and also had a lot of text blocks duplicating/switching places or disappearing. Sorry this isn't more specific, just not sure what exactly is the trigger here. A lot of artworks, maybe?

in Writer:

![screen shot 2015-03-17 at 17 30 34](https://cloud.githubusercontent.com/assets/10982707/6698069/d4646d9e-cccb-11e4-89b9-3f7cf7c286e1.png)

on site:

![screen shot 2015-03-17 at 17 30 42](https://cloud.githubusercontent.com/assets/10982707/6698071/d7556198-cccb-11e4-95a6-198c7db61896.png)

**Comment by craigspaeth** [comment]
This is fixed in production now.
