### ISSUE TITLE
featuring to fair pages not working

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#227]
couple of times recently we've featured a post to a fair through Writer and it hasn't shown up on the microsite:

![screen shot 2015-03-18 at 12 42 59](https://cloud.githubusercontent.com/assets/10982707/6714118/00fef620-cd6d-11e4-9e56-4ed6ca61fc67.png)

![screen shot 2015-03-18 at 12 43 11](https://cloud.githubusercontent.com/assets/10982707/6714120/04f081fe-cd6d-11e4-811e-f19567544f1f.png)

[NOTE: I added this one manually to the microsite (via old admin), so it's showing up there now)

**Comment by craigspaeth** [comment]
@halleyjohnson: How do you feel about launching fair magazines across the board now that it worked out for The Armory Show?

**Comment by halleyjohnson** [comment]
@craigspaeth I feel very good about that! Checked with Molly as well, thumbs up.
