### ISSUE TITLE
Admin can change slugs and the publish date of an article

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#232]
![image](https://cloud.githubusercontent.com/assets/555859/6806712/db73659a-d220-11e4-8c40-f3c4f090af81.png)

**Comment by craigspaeth** [comment]
@kanaabe: Feel free to PR these separately. These will likewise need updates to the Writer API to allow changing from the client.

For slugs: I would like whatever the admin saves in that input to be the first item in the `slugs` array and ensure that slugs are `_.unique` so there's no duplicates.

Publish date: If the client sends `published_at` override [this](https://github.com/artsy/positron/blob/master/api/apps/articles/model.coffee#L164 and make sure to save a proper `Date` object to the db.

(Date picker is extra credit, so def. don't get caught up on that)

**Comment by kanaabe** [comment]
Ok, thanks for breaking this down!

**Comment by craigspaeth** [comment]
Fleshed out states:

![image](https://cloud.githubusercontent.com/assets/555859/6806916/f513d664-d221-11e4-8c18-5701ab4d774d.png)
