### ISSUE TITLE
still a bit of a formatting issue with copying from google docs

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#238]
It seems random (which I know is the worst feedback) but about 1/3 of the time when I paste a paragraph directly from Google docs it all goes bold. I tried to see if this was limited to text with links in it or already with some bolding/other formatting, but it can be with straight text too. The best I can do is share a doc with you and show you which ones pasted in bold.

(Not a high priority, as most text is working fine—just highlighting that this isn't 100% smooth yet.)

**Comment by craigspaeth** [comment]
I've seen that weirdness happen before too. If you ever come upon a sample doc that does that please share it with me and it shouldn't be too hard to fix.
