### ISSUE TITLE
edits loading on the site before article is saved in Writer

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#239]
I was editing this post: https://www.artsy.net/article/daily-digest-top-art-news-opening-tonight-in-new-york-6

And the edits I was making in Writer were going live on the site (upon refresh) before I had saved anything in Writer. Just had the draft open and was making some continuous edits.

**Comment by craigspaeth** [comment]
@halleyjohnson: You bring up a good point... Writer auto-saves, which will publish changes immediately. We probably need to do be more clever about this and disable auto-saving if the article is published (with a message saying "you have unsaved changes" in case you try to close the window expecting auto-save). I'm going to move this out of Launch items b/c it's not trivial to implement and not crucial to a v1 UX.

**Comment by halleyjohnson** [comment]
That seems like a good solution, I think in the meantime it would be good to add some kind of notification of this? I can let the team know but it is always good to remind people, probably.

**Comment by craigspaeth** [comment]
@halleyjohnson: For sure. I think it's definitely one of the most important items to implement right after rollout b/c that could shock someone who discovers that unexpectedly.
