### ISSUE TITLE
Double-synced post

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#240]
I think what happened here is that we made the article, synced it to post, and the post somehow migrated as an article again? Not sure, but there are two posts in Writer now: http://cl.ly/image/3b0s1h223218

And the bottom one has the slideshow thing at the top that happens when a post migrates.
https://writer.artsy.net/articles/5501cfcb7261694de4110000/edit

I think because we made it an article on the site, they're all redirecting to the right place, but flagging this as a test case and also not sure how to safely clean it up.

**Comment by halleyjohnson** [comment]
Same thing here, the second one in the list has the slideshow: http://cl.ly/image/241z3G1h1y2D

Is this just an unavoidable migration thing? If so, how can I clean these up when I find them?

**Comment by craigspaeth** [comment]
@halleyjohnson: You can delete posts on front-end as much as you want and then go back to Writer and re-sync to post to fix dupes. After rolling out Writer I'll also make a pass at cleaning up any migrated dupes or oddities.
