### ISSUE TITLE
disappearing article

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#241]
I used the URL editing method to bring up this post in Writer the other day: https://www.artsy.net/post/editorial-the-top-10-chinese-artists-not-named (you may remember I had some issues with it)

When I was editing the article, which I definitely saved a few times publicly, the URL that came up was this: https://www.artsy.net/article/artsy-editorial-the-top-10-chinese-artists-not-named-ai

This was also where the post was redirecting when I just changed the URL from /post/ to /article/ to view the corresponding article.

Now the article I created there is gone both on the site and in Writer, and the post is redirecting to the regular URL with /article/ in it instead: https://www.artsy.net/article/editorial-the-top-10-chinese-artists-not-named

But just has the slideshow and none of my edits. Do we know why the first, different URL came up at all? And then why that article got deleted?

**Comment by craigspaeth** [comment]
Noting: Could have something to do with the migration script. Seems like it tried to turn these articles into migrated posts.

**Comment by halleyjohnson** [comment]
They were already migrated articles before I edited them, just noting. But
at the different URL?

On Friday, March 20, 2015, Craig Spaeth <notifications@github.com> wrote:

> Noting: Could have something to do with the migration script. Seems like
> it tried to turn these articles into migrated posts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/positron/issues/241#issuecomment-84063203>.
>


-- 
Halley Johnson
Editorial Associate
Artsy <http://artsy.net/>  ⁄  401 Broadway, 25th Floor, New York, NY, 10013

halley@artsy.net

Artsy Editorial <https://artsy.net/posts/featured>

**Comment by craigspaeth** [comment]
@halleyjohnson: To be clear were these old posts (not originally created in Writer) that you edited to look better?

If so I think what's happening is the migration script isn't being smart about "merging" old posts updated in Writer, and instead it's replacing these articles with data from the post form of it—causing it to potentially lose slug history.

I think the best course of actions now that the old posting tool isn't being seriously used by anyone is:

1. I'll restore the articles that were damaged  by the migration script this way
2. I'll update the migration script to only add new posts written by the old posting tool without attempting to remove dupes or do any merging trickier. (If we end up with some dupes of old articles we can make a pass to clean this up after rollout).

**Comment by craigspaeth** [comment]
Also it would be helpful if you could link to some other articles that were affected by this.

**Comment by halleyjohnson** [comment]
Yes, so I didn't find them in Writer, I brought them up by manipulating the URLS (writer.artsy.net/articles/SLUG/edit) and they already had the slideshow up top, so I assumed they had been migrated in already (just live somewhere far back in the published posts and didn't want to dig them up that way).

To me the still confusing part is how they came up with a new, unusual URL for my initial edit—https://www.artsy.net/article/artsy-editorial-the-top-10-chinese-artists-not-named-ai instead of just converting the old post URL into article directly—which would have been https://www.artsy.net/article/editorial-the-top-10-chinese-artists-not-named AND is where it reverted to when the changes disappeared.

I can find an old post that's not too important and try editing it the same way to duplicate the error? I haven't been editing old posts since this happened to try to avoid this issue cropping up again. First time it's happened to me.

**Comment by craigspaeth** [comment]
@halleyjohnson: No need to try to duplicate the problem. I just want to be able make sure I'm finding the articles that were affected by this. If it's only a handful then maybe I can just restore them on a case-by-case basis.

**Comment by halleyjohnson** [comment]
As far as I know it's just those two, but I'm going to be working on a number of posts like this in the next week, so could potentially trigger it again.

**Comment by craigspaeth** [comment]
@halleyjohnson: Cool cool. I'll get a fix to the migration clobbering in this weekend and it won't be a problem going forward.

**Comment by craigspaeth** [comment]
@halleyjohnson: I restored https://www.artsy.net/article/artsy-editorial-the-top-10-chinese-artists-not-named-ai but I didn't have as much luck with https://writer.artsy.net/articles/editorial-10-contemporary-turkish-artists-you-should-know/edit. If it's not too much work do you mind just sorting that latter one out manually?

I also fixed the migration script so you're free to edit old posts in Writer without worrying about this issue popping up again.

Thanks for all of the help tracking this down!

**Comment by halleyjohnson** [comment]
Wonderful, thanks @craigspaeth ! No worries on that second one, magic that you got the first one back.
