### ISSUE TITLE
Articles are featuring to Magazine when edited

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#299]
I re-formatted a bunch of posts from last year in advance of our SP-Arte launch, and all those articles are now showing up on Magazine at the top of the feed.

Related: weren't we planning to add the year of publish date if it's over a year old, or maybe 6-8 months might be better? These are showing up as just the month and day:
![screen shot 2015-03-30 at 12 19 46](https://cloud.githubusercontent.com/assets/10982707/6900902/b521f9ae-d6d7-11e4-8456-16e9c1cba0b9.png)
![screen shot 2015-03-30 at 12 19 55](https://cloud.githubusercontent.com/assets/10982707/6900905/b8c371c8-d6d7-11e4-81ef-d6c7daf1a0e5.png)

**Comment by craigspaeth** [comment]
Sorry this was just me filling up magazine for today's demo. Please feel free to un-feature these and I'll back-fill magazine with editorial's articles.
