### ISSUE TITLE
partner profile articles out of sync

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#300]
just one example, I'll look further. This is the /posts feed for Mark Moore Gallery: https://cl.ly/2o071Y2K3y0a?_ga=1.261088653.1842824099.1425588408

So, 1. editorial post on four photographers, 2. partner's post on megan smythe, 3. editorial post on umbrico, 4. editorial post on mixed-media artists, 5. partner's post on david maisel (and so on)

Here's the /articles feed, where posts 2 and 5 are at the top and posts 1, 3, and 4 nowhere to be found:
![screen shot 2015-03-30 at 13 30 53](https://cloud.githubusercontent.com/assets/10982707/6902391/967d2e92-d6e1-11e4-9cb8-5ed05558f59d.png)

Checked in Writer and post 1 was featured to partner's page in admin, posts 3 and 4 were not (we made them before that feature was enabled), but all three have been featured manually (via the old admin) to the partner's profile.

**Comment by halleyjohnson** [comment]
Hey @craigspaeth this page is still not in sync. Post 1 is there now, but there should be two more editorial posts between the gallery's posts about Megan Smythe and David Maisel. Maybe we should sync up in person about this today? Just want to make sure the featuring we've done to the backlog is going to migrate over, or what we need to do on our end to check that everything's in order.

![screen shot 2015-04-01 at 10 46 58](https://cloud.githubusercontent.com/assets/10982707/6943504/871170e0-d85c-11e4-96ae-4f3cb03e926e.png)

**Comment by halleyjohnson** [comment]
Another example: on Rod Barton's page in the new articles preview (I'm accessing via labs), only their most recent post, featured through Writer, is showing up. But this post, featured via the old admin button, should also be there: https://www.artsy.net/post/editorial-camilla-steinums-textile-sculptures-take-a-feminist

![screen shot 2015-04-01 at 10 57 21](https://cloud.githubusercontent.com/assets/10982707/6943767/26ea8e5c-d85e-11e4-82bc-a16c896af8af.png)

**Comment by craigspaeth** [comment]
Example https://writer.artsy.net/articles/54df78a97920db0400040da7/edit. It was written in Writer before we could associate partners and it is featured via the old posting system.

We need to...
* distinct the `gravity_id`s from articles
* find the posts from Gravity by those ids
* Ensure that the article has partner_ids of any partners the post is feature to
