### ISSUE TITLE
Rollout todos

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#301]
- [x] Follow up communications with Institutions/Galleries
  - [x] sample invite email
  - [x] using Writer on behalf of your partner playbook
- [x] Ensure intercom is set up (+ discuss integration w/ Waves/etc.)
- [x] Backfill Magazine
- [x] Ensure PPPs migrated posts are good
- [x] PR out of labs

**Comment by halleyjohnson** [comment]
@craigspaeth Not sure if this is the best place for this, but starting a list of other authors we can backfill Magazine with besides Artsy Editorial:

https://www.artsy.net/matthew
https://www.artsy.net/francesca-gavin

**Comment by craigspaeth** [comment]
Thanks @halleyjohnson, great place to do it!
