### ISSUE TITLE
artwork sizing issue

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#302]
Not sure if this is just a specific case of these particular artworks, but have two sizing issues in a row in this post: https://www.artsy.net/article/artsy-editorial-the-top-10-chinese-artists-not-named-ai

I tend to think this can look okay if the captions hug the images, but I don't think that's what we've been going for in general—rather, the images should all be the same height, correct?

![screen shot 2015-03-30 at 18 20 50](https://cloud.githubusercontent.com/assets/10982707/6908237/a847c114-d709-11e4-878e-57dd22f20176.png)

**Comment by craigspaeth** [comment]
Yeah there's got to be something weird going on in the logic there, it should try to match the heights at any cost.

https://github.com/artsy/jquery-fillwidth-lite
