### ISSUE TITLE
bolding/unbolding doesn't work with H2

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#306]
I think you noticed this in demo yesterday @craigspaeth but you can't bold/unbold text once it's in H2 format, have to take it out, bold/unbold it, then re-H2 it.

**Comment by kanaabe** [comment]
This looks like a [limitation](https://github.com/guardian/scribe/blob/884c2c27c763ad965e9de5a8f27926c5417bc62d/src/plugins/core/patches/commands/bold.js#L15-L16) in scribe-editor's patches for the bold command. 

I played around with enabling it in a header anyway and when testing in Chrome, it seemed to look okay. I wonder what they mean by corrupting the markup?
