### ISSUE TITLE
changing date doesn't change order of posts on profile page

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#315]
Just changed the date of the top post to February 2nd, should put in second place.

![screen shot 2015-04-02 at 10 49 43](https://cloud.githubusercontent.com/assets/10982707/6966341/53ab9c38-d926-11e4-9c38-dfbd74823946.png)

**Comment by kanaabe** [comment]
Hi Halley, are you still seeing this? Possibly just took some time for the update to occur. I'm seeing the Paul Rand article on top and the FLW article below that. It looks like we have different views though, not sure what that's about. My screenshot below. 

![2015-04-02_1111](https://cloud.githubusercontent.com/assets/2236794/6966732/3819e580-d929-11e4-8de4-f675f0d0b483.png)

**Comment by halleyjohnson** [comment]
Hey Kana, I'm in the "articles" lab—which I'm assuming is how things will look after we flip the switch? I haven't been worrying too much about how things look on the post end. Still swapped for me, though:
![screen shot 2015-04-02 at 11 17 25](https://cloud.githubusercontent.com/assets/10982707/6966864/de8e5464-d929-11e4-8a93-9eb0ca4e5f06.png)

**Comment by kanaabe** [comment]
Ohh I see. Got it. I'll look into this, thanks.

**Comment by kanaabe** [comment]
Ok, i fixed it for now, but it seems like the order of the articles is actually just based on last saved. Sorry, that was bad QA on my part as I assumed it would automatically order based on the published_at date. 

Probably a fix on Force but lets keep this open here until it's resolved.

**Comment by halleyjohnson** [comment]
Is that the case only for these profile pages? I think on Magazine, publish date is what dictates the order, not last saved.

**Comment by kanaabe** [comment]
Yep, you're right. I just PR'd on Force so fix is coming shortly! :bear:

**Comment by kanaabe** [comment]
This is now merged: https://github.com/artsy/force/pull/2411

**Comment by halleyjohnson** [comment]
Beautiful, thanks Kana!

**Comment by halleyjohnson** [comment]
@kanaabe, I'm still having this problem: https://www.artsy.net/aca-galleries/articles

The top post was just edited, publish date is correct, but it should be third in the feed.

![screen shot 2015-04-03 at 17 08 23](https://cloud.githubusercontent.com/assets/10982707/6988941/16e3ebda-da24-11e4-9644-34ffecf36ead.png)

**Comment by kanaabe** [comment]
PR'd on Force

**Comment by kanaabe** [comment]
https://github.com/artsy/force/pull/2427/files
