### ISSUE TITLE
saving is updating publish date

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#318]
I just edited a post and it now says it was published today:

https://www.artsy.net/article/artsy-editorial-a-journey-to-mexico-with-sarah-lucas-through

![screen shot 2015-04-03 at 16 53 59](https://cloud.githubusercontent.com/assets/10982707/6988721/24afaa94-da22-11e4-9c1d-dd812f719c5a.png)

**Comment by halleyjohnson** [comment]
It's not coming to the top of the Magazine feed, though, just showing up on the article page as published today.

**Comment by kanaabe** [comment]
@halleyjohnson Were you able to reproduce this issue again?

**Comment by halleyjohnson** [comment]
@kanaabe No, haven't had the problem again, and I've been editing old posts pretty frequently. I'll update here if I see it come up.
