### ISSUE TITLE
Style sidebar like new CMS sidebar

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#321]
Even though Writer doesn't need the space right now, it would be nice to keep these consistent and be able to say "Writer" to the side of the logomark.

![image](https://cloud.githubusercontent.com/assets/555859/6994735/48efa6a4-daf2-11e4-865a-2e59a3f9cff8.png)

**Comment by dylanfareed** [comment]
FWIW we partially updated the sidebar in CMS to give Writer the space to go its own way. They were close before but not identical so it seemed better to take a slightly different approach. 

The other consideration was that in CMS we are going to add additional sidebar items and we wanted to leave some flexibility with vertical space which may not be as big of an issue in Writer.

**Comment by craigspaeth** [comment]
Good point. I'll close this as a nice-to-have, not to be implemented any time soon.
