### ISSUE TITLE
Insider picks UI

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#322]
- Admin can send a private link to a view of all works at a fair
- A user viewing those works can select their favorites
- An admin can click a button and convert those picks into an article

Something like (design TBD):

![image](https://cloud.githubusercontent.com/assets/555859/7009779/ac00b048-dc6a-11e4-9199-e8630ecdf955.png)

**Comment by craigspaeth** [comment]
@broskoski: @halleyjohnson: Feel free to add any notes to this issue. Basically we discussed a need to retire the "fair preview" app in favor of separate functionality in Writer & the admin-fairs app.

**Comment by dylanfareed** [comment]
A couple notes here:

* want to make sure we never display private_partner booths in this list - https://github.com/artsy/gravity/blob/master/app/api/v1/fairs_shows_endpoint.rb#L13
* Its not clear to me whether the commenting permitted in the current system is meaningful or used with any frequency, but that exists in the current system (commenting on each pick)

**Comment by halleyjohnson** [comment]
@dylanfareed The commenting is definitely important.

**Comment by dylanfareed** [comment]
Good to know. We've actually been using this for more than a year, maybe we can get a summary of by and large how this is used (for admins and insider picks) and whether there are some cases that use some subset of the features--for example, marking a review as "done" or not. 

This would make the rebuilding (if that happens) more clear.

**Comment by craigspaeth** [comment]
Notes from convo with Molly:

Low-tech is fine to a degree. The most important part is being able to view unpublished works from a fair "live" b/c the contributors wait to the very last second and people are uploading/changing stuff up to the last minute as well.

The view of works should ideally have some basic sorting/grouping to be able to better scan it. By exhibitor or A-Z would be helpful.

Interesting nice-to-have is that Molly mentioned a lot of these contributors are high value collectors whose first experience with Artsy could be this UI—there's an opportunity to convert them into Artsy users via some end-of-process CTA.
