### ISSUE TITLE
Institutional partner profiles not updated

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#324]
This list isn't exhaustive, but including a few examples below—not sure how these partners are classified differently from gallery partners, but the cleanup didn't seem to catch their pages. There were a mix of personal posts (ie. from these partners) and Editorial/internal posts (some from Institutional team members, like Christine, Janet, Liz...).

https://www.artsy.net/guggenheim/articles (I just manually added the one that is there)
https://www.artsy.net/jeu-de-paume/articles (I know this one was there: https://www.artsy.net/article/christine-the-ultimate-photographers-show-garry-winogrand-at)
https://www.artsy.net/fondation-cartier/articles
https://www.artsy.net/risdmuseum/articles
https://www.artsy.net/metmuseum/articles
https://www.artsy.net/thedrawingcenter/articles

**Comment by craigspaeth** [comment]
@halleyjohnson: I ran the script that I ran for galleries and this should be fixed now. Lemme know if you find anything else related that's out of wack.

**Comment by halleyjohnson** [comment]
Woot! @craigspaeth
