### ISSUE TITLE
VB priorities

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#328]
Must have:
+ full-bleed videos
+ landing page-specific functionality (one would be sticky posts—also in the bottom of VB articles)

Nice to have:
+ potential maps feature
+ thumbnail image editing
+ Marina has said that having individual bylines available for this content while retaining the Editorial umbrella would be a big win since we'll be likely seeing a large amount of traffic
+ I'd suggest folding the potential to hyperlink uploaded images into this list, if possible

(@craigspaeth I think you also took some notes in this meeting, would appreciate your checking that list as well for anything to add to this list)

**Comment by halleyjohnson** [comment]
@craigspaeth Any updates on this list? I'm thinking you are discussing some of this directly with Marina, but just checking in if anything I can help with/relay to Editorial on these asks.

**Comment by craigspaeth** [comment]
@halleyjohnson: I've been mostly in contact with Owen about feature sets. Working out the larger "Verticals" structure now, will sync up when I get more granular.

**Comment by halleyjohnson** [comment]
@craigspaeth Did thumbnail image editing and hyperlinking uploaded images make it on the main list? Should I start a longtail VB priorities list somewhere?

**Comment by halleyjohnson** [comment]
Update: what's left before Monday's launch

full-bleed videos (and content input above headline?)
update hard-coded copy/images on feature page

@craigspaeth Can we sync up on any issues here today?

**Comment by craigspaeth** [comment]
Feature-wise we're prepared here, just a matter of updating the hard-coded stuff manually. Gonna close this.
