### ISSUE TITLE
Soft returns not working

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#331]
Soft returns are rendering like paragraph breaks. 

![screen_shot_2015-04-09_at_11 15 27_am](https://cloud.githubusercontent.com/assets/3196536/7078176/c536082a-dee4-11e4-9ae1-2e09641e6c58.png)

Space between "United States Pavillion" and the show title should be smaller

**Comment by craigspaeth** [comment]
So it's pretty tricky to accommodate soft returns and varying font-sizes inside of a header... b/c WYSIWG :neutral_face: (happy to explain in detail if you want).

Before you had a version where the text was in avant garde and more like a different form of header. That would actually be easier to implement if that's ideal. It would act kind of like how Medium has h1, h2, h3 that can play together.

e.g.

![image](https://cloud.githubusercontent.com/assets/555859/7446800/3ed85842-f1b2-11e4-8782-40da373321ef.png)

Let me know if that works and I will gladly implement that instead.

**Comment by craigspaeth** [comment]
@owendodd @halleyjohnson ^^

**Comment by owendodd** [comment]
Sounds great to me! Thanks!
