### ISSUE TITLE
hide "no articles" text on profiles

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#332]
as a quick fix for the missing author pages. maybe a good idea to do in general, as it makes pages which are living as general bio pages look like they're broken (same with partner profiles which have no posts)

**Comment by kanaabe** [comment]
@halleyjohnson Do you think you can clarify this a little? What is the issue, how do I reproduce it, an example, etc? Thank you!

**Comment by halleyjohnson** [comment]
@kanaabe have discussed this at length with @craigspaeth who may have some insight, but generally:

When a user has no posts or favorites their profile turns up a "[User] has no articles." text by default. We'd like to have this removed, as there are many links in old articles to our contributors (example below) who have not authored any articles from their personal accounts but whose profiles can be accessed nonetheless. This will make these pages more like static bio pages until we have addressed the whole user/contributor/organization overhaul. 

My second not there was just that it could be good to remove this from all profiles (not just contributors) since we aren't granting Writer access to individuals at this point and it turns up broken-looking pages for users without favorites or articles.

https://www.artsy.net/arsalan-mohammad

![screen shot 2015-04-20 at 13 37 13](https://cloud.githubusercontent.com/assets/10982707/7236347/615539a8-e762-11e4-8804-fd4d118e1ef8.png)

Note this doesn't happen to my profile since I have favorites:

https://www.artsy.net/halley-johnson

![screen shot 2015-04-20 at 13 38 16](https://cloud.githubusercontent.com/assets/10982707/7236366/837e8354-e762-11e4-8f52-5ddefb4a9b3e.png)


Happy to provide more examples if needed.

**Comment by craigspaeth** [comment]
@kanaabe: This issue is more of a design question right now. I added a needs design label—feel free to move on to something else in the meantime.

**Comment by halleyjohnson** [comment]
@craigspaeth I thought we were going to try to just patch this quickly, to remove that text from author pages so they don't show up looking broken for people who click through? I don't know how complicated it is to just hide that text until further decisions are made, but if doable, it would be much better to have these pages looking clean.
