### ISSUE TITLE
Articles showing up on artist pages with wrong author

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#334]
All the articles on Cai Guo-Qiang's artist page say they're by Artsy Editorial—all the ones in the screenshot below are not. Links follow. The correct authors appear on the article pages.

![screen shot 2015-04-10 at 18 18 50](https://cloud.githubusercontent.com/assets/10982707/7098432/4f326c98-dfae-11e4-8f56-240b7e22d798.png)

https://www.artsy.net/article/caistudio-vivid-memories-at-fondation-cartier
https://www.artsy.net/article/art21-cultural-identities-ai-weiwei-cao-fei-and
https://www.artsy.net/article/caistudio-falling-back-to-earth
https://www.artsy.net/article/cai-studio-full-body-scan-next-in-conversation-with-cai
https://www.artsy.net/article/cai-studio-home-on-a-matchbox

**Comment by craigspaeth** [comment]
Whoops! I think "Artsy Editorial" is hard coded from before denormalizing `article.author`.

@robertlenne: Should these look like the thumbnails in Magazine now?

![image](https://cloud.githubusercontent.com/assets/555859/7139975/073a45e6-e297-11e4-8b15-e5b04548c667.png)

**Comment by robertlenne** [comment]
Can we keep current form factor? It's to get more text on the page so they are less thin from an SEO standpoint.
