### ISSUE TITLE
can manually select "big box" and "sidebar" articles on Magazine landing page via Writer

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#335]
Would be great to control these directly rather than updating the timestamps to force them into the correct places.

Thinking of this like two checkboxes in Writer, one for big box and one for sidebar, and the last three posts checked in sidebar will be there (then the bottom ones get pushed out as more are added to the top) and the big box goes away if another article is checked for the big box. You could check both boxes if you want the big box article to go to the sidebar once another is checked for big box (though it would skip the sidebar if three new sidebar boxes were checked in the meantime). 

This may be very confusing and not sensible, please let me know/we can talk in person if you want.

Thinking some version of this may be implemented for the VB page anyway?

**Comment by halleyjohnson** [comment]
@craigspaeth Any update on when this is coming?

**Comment by craigspaeth** [comment]
Currently outside of the VB scope. But we can add it to a long tail of VB features in case we're early on the deadline.

**Comment by kanaabe** [comment]
Closing this in favor of: https://github.com/artsy/positron/issues/121
