### ISSUE TITLE
newest article showing up last in partner feed

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#346]
https://writer.artsy.net/articles/54e74062c128010600b8e482/edit

https://www.artsy.net/sabrina-amrani-gallery/articles

![screen shot 2015-04-17 at 19 05 19](https://cloud.githubusercontent.com/assets/10982707/7212429/b4b58b46-e534-11e4-846a-e6aea8729bf7.png)

**Comment by kanaabe** [comment]
I fixed this one article during testing by editing the publish date and resaving the article. Do you have any more examples of this to test? Are you repeatedly seeing this issue?

**Comment by halleyjohnson** [comment]
@kanaabe I haven't seen it again, to my knowledge—I think this was just an early migration issue. Think it's safe to close, and I'll keep an eye out for more. Thanks!
