### ISSUE TITLE
Pagination limits

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#352]
Apparently 500 items isn't a perf. bottleneck currently, but there needs to be some kind of limit.

**Comment by dzucconi** [comment]
0_0

How big is a 500 item JSON response anyway?

**Comment by craigspaeth** [comment]
Way too big (3mb)! I accidentally added a 2 on the end of the `limit` in Force!! https://github.com/artsy/force/blob/master/apps/articles/routes.coffee#L17

Not a bottleneck on the server, but def. on the client
