### ISSUE TITLE
Compatibility with sitemaps and pre-rendered pages

### ISSUE THREAD

**Issue by joeyAghion** [artsy/positron#359]
New-style articles are not reflected in sitemaps.

Our old solution for this was for Gravity to iterate through published `Post`s and generate the [sitemap index](https://www.artsy.net/sitemap.xml) and [individual sitemaps](https://www.artsy.net/sitemap-posts-2.xml) for storage on S3, where Force would proxy to. Reflection would crawl those URLs and pre-render the pages for Google.

If /article pages are completely server-rendered, they should _not_ include the fragment `meta` tag. If they're rendered client-side, they should continue to include the tag, but must be listed in the sitemap so that Reflection can pre-render them.

Since Gravity doesn't "know" about Articles, maybe it should just include one sitemap-articles.xml in its index, and Positron should be responsible for writing that to S3.

**Comment by broskoski** [comment]
Extra context here from Taktical:

"Google requires a special XML sitemap for news.  Make sure that the sitemap doesn't include articles more than 5 days old. Here's a link explaining how to set that up: https://support.google.com/news/publisher/topic/2527688?hl=en&ref_topic=4359874"

Could this just be a route that positron generates dynamically whenever requested? Get all articles less than 5 days old, iterate over, etc.

**Comment by craigspaeth** [comment]
Thinking it might make sense to aggregate this with api endpoints...

Reading over the [Bezos manifesto for SOA](http://java.dzone.com/articles/getting-soa-right-%E2%80%93-thinking) I think it makes the most sense for Force (b/c it knows the routing structure) to put together sitemaps through RESTful endpoints...

> no other form of interprocess communication allowed: no direct linking, no direct reads of another team’s data store, no shared-memory model, no back-doors whatsoever

That means Force needs to pull out slugs for various resources—we can start this ball rolling by exposing the slugs of articles. Expecting the client to parse the full article data feels too clumbsy IMO. We can do better...

1. GET /api/articles?fields=slugs&published=true
  This seems to be the [pragmatic REST](https://blog.apigee.com/detail/restful_api_design_can_your_api_give_developers_just_the_information) suggestion. But then the client would still have to request a bunch of pages to get the full data or we make an exception on the `limit` param if `fields=slugs` is specified. This `fields=` stuff could be generalized too, but not much of an apparent need for that right now.

2. GET /api/article_slugs
  An endpoint that is totally catered to the sitemap use case and would return `{ total: Number, count: Number, results: ['slug','other-slug']}. Would be simplest for client to consume, but a minor offense to REST guidelines.

More food for thought... either option we'd want params to be able to filter out articles that are "not paid content, within a publish date, and w/e else is necessary for Google News".
