### ISSUE TITLE
UI to manage verticals

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#376]
A bunch of mobile-first form fields to keep it simple to implement.

![vertical](https://cloud.githubusercontent.com/assets/555859/7622979/6633c518-f9a3-11e4-9e57-803b1576a12b.png)

A couple things to note:

* Desktop layout is a 900px container with 30px gutters. This is the same layout as the admin panel inside of articles and we should probably componentize this a bit more.
* The autocomplete select component is used here in selecting featured articles... so maybe make sure that works well responsive
* Probably makes sense to better componentize the upload form UI used in articles and here.
* The "new" and "edit" UI is shared here for simple implementation. So clicking "Add Vertical" brings up an empty state of the form, then clicking "Save Changes" goes back to the list view. Likewise clicking on a vertical brings up the from UI filled in and clicking save goes back.
* Verticals icon in the sidebar is TBD so feel free to re-use the "published" icon for now

**Comment by craigspaeth** [comment]
@halleyjohnson: Noted that the "sticky articles" should actually be more like featured links e.g. Thumbnail + Title + Abitrary Url

@owendodd I think the original intention of these were to be articles. Let me know if you have thoughts on if introducing that kind of flexibility should impact the design.

![image](https://cloud.githubusercontent.com/assets/555859/7656985/45cee654-fafc-11e4-9c2e-0e4dfba8eebc.png)

**Comment by owendodd** [comment]
@craigspaeth That makes sense to me, I don't think it should have any impact on the design.

**Comment by craigspaeth** [comment]
Updated the last two sections given the flexibility of the "sticky links"

![image](https://cloud.githubusercontent.com/assets/555859/7732704/b9898ef6-fef7-11e4-8c08-194663b7f0ec.png)

**Comment by owendodd** [comment]
Woo! 🎉
