### ISSUE TITLE
Formatting not syncing from Google docs into Writer style

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#379]
This may be related to the fix you pushed for soft returns—I think it started around the same time.

When pasting in formatted content (italics, bold) from Google docs now, they're retaining the fonts, sizes, and colors from the google doc instead of syncing over to Writer format. You can fix this by re-italicizing or bolding it (very time-consuming for posts with a lot of formatting). I also showed you the small caps "trick"/bug which I think is the same issue. Can provide more examples if you like.

in google doc:
![screen shot 2015-05-05 at 11 56 43](https://cloud.githubusercontent.com/assets/10982707/7477399/85ed6ce8-f321-11e4-99a8-6312d1249531.png)

after pasting directly in:
![screen shot 2015-05-05 at 11 56 35](https://cloud.githubusercontent.com/assets/10982707/7477410/9edb5ad0-f321-11e4-9a8d-f6db91524e09.png)

after re-italicizing and bolding (correct format):
![screen shot 2015-05-05 at 11 57 03](https://cloud.githubusercontent.com/assets/10982707/7477418/ac52f4c0-f321-11e4-8ac1-3e72104899e6.png)

**Comment by halleyjohnson** [comment]
Another example (note the italicized words):

after pasting
![screen shot 2015-05-05 at 16 00 31](https://cloud.githubusercontent.com/assets/10982707/7481719/2032ed82-f340-11e4-8dde-6973341a186c.png)


after fixing manually in Writer
![screen shot 2015-05-05 at 16 00 11](https://cloud.githubusercontent.com/assets/10982707/7481721/24ce1272-f340-11e4-9457-aff94be5ca3e.png)

**Comment by craigspaeth** [comment]
Seems like Copy + Paste can let in some weird HTML. Need to make sure we're not stepping on https://github.com/guardian/scribe-plugin-sanitizer toes.

**Comment by craigspaeth** [comment]
@kanaabe Feel free to bounce this back as it'll be tricky, but if you're up for the challenge it involves debugging with Scribe plugins.

**Comment by halleyjohnson** [comment]
@kanaabe @craigspaeth This bug has not changed for me and other Ed. team members I've checked with. I've tried logging out and in, working in incognito, nothing is jogging it — see sample doc and draft below for text that doesn't work for me.

https://docs.google.com/a/artsymail.com/document/d/19yxh7x6VjaMNf1Uqu7xrP1eLpnv0NSpO6AR1Wj3aZvQ/edit?usp=sharing

https://writer.artsy.net/articles/55772b5b4d4acd0600564ee9/edit

**Comment by kanaabe** [comment]
@halleyjohnson Hi, this hasn't been deployed yet because we haven't pushed the latest version of scribe-google-docs up to npm. I'll just directly include the github link for now in `package.json`. Should be about 30 minutes! Sorry for the delay.

**Comment by halleyjohnson** [comment]
Thanks for updating, @kanaabe !

**Comment by kanaabe** [comment]
Ok this is fixed for real now! Check it out.

**Comment by halleyjohnson** [comment]
@kanaabe Hate to throw this back open, but a slight issue still sticking around. See image below—when text is hyperlinked, it's appearing blue (as it does in google docs automatically).

![screen shot 2015-06-11 at 1 06 22 pm](https://cloud.githubusercontent.com/assets/10982707/8133342/d202f552-10f5-11e5-9a94-fade05b30d43.png)

**Comment by kanaabe** [comment]
Oh I see, this is happening because sanitize doesn't rip out styling from nested elements. Fix coming soon. Regular links should be working, just not bold/italicized ones.

**Comment by craigspaeth** [comment]
W00t! Killing it Kana! We probably want to actually clean out any nested elements that aren't `<strong>`/`<b>`/`<i>`/`<em`>,etc. ... which [this plugin should address](https://github.com/artsy/positron/blob/master/client/apps/edit/components/section_text/index.coffee#L50) (maybe the order of plugins needs to be different)... but as you discovered before there might be `font=` attributes on those tags that still need to be addressed that `scribePluginSanitizer` isn't addressing.

**Comment by halleyjohnson** [comment]
That's right, @kanaabe — just realizing that also when a line is bolded _and_ italicized, after pasting it only retains the bolding.
