### ISSUE TITLE
Tier 1 posts not displaying on VB mobile page

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#380]
Excuse the horrible iPhone-printed PDF, but see this file (http://halley.dropmark.com/232646/4757347) for current state of mobile VB page. The Tier 1 posts (links below) aren't showing up on this page.

![screen shot 2015-05-05 at 12 54 55](https://cloud.githubusercontent.com/assets/10982707/7478054/f562c93e-f325-11e4-9e52-9578087c6bb7.png)

https://www.artsy.net/article/artsy-editorial-behind-the-venice-biennale-2015-a-short-history-of-the-world-s-most-important-art-exhibition
https://www.artsy.net/article/artsy-editorial-behind-the-venice-biennale-2015-bgl-builds-a-canadian-corner-store-in-venice
https://www.artsy.net/article/artsy-editorial-venice-biennale-2015-british-pavilion-sarah-lucas
https://www.artsy.net/article/artsy-editorial-venice-biennale-2015-united-states-pavilion-joan-jonas

**Comment by craigspaeth** [comment]
Moved this to Microgravity: https://github.com/artsy/microgravity/issues/850
