### ISSUE TITLE
Admins can explicitly curate the top 4 articles of a vertical

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#394]
This part

![image](https://cloud.githubusercontent.com/assets/555859/7639645/7fdff470-fa4b-11e4-842f-b4e6ce84a357.png)

**Comment by halleyjohnson** [comment]
@craigspaeth Does this count for the Magazine feed as well? A big want.

**Comment by kanaabe** [comment]
Closing in favor of https://github.com/artsy/positron/issues/121
