### ISSUE TITLE
When uploading an image, it should not try to preview client-side for large files

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#401]
Or it will crash the browser.

**Comment by kanaabe** [comment]
Hmmm, do you have an example image that breaks? I just tried uploading a variety of image sizes up to 31MB, all of which worked and didn't crash.

**Comment by craigspaeth** [comment]
Your computer is too powerful!! Hmm dunno, I just know I've gotten this complaint from editorial before. It might be worth trying something like an uncompressed .tiff or .png—maybe it's more about the file type. Otherwise I can suggest opening 100 Artsy tabs to mimic the set up of some user's machines here.

**Comment by kanaabe** [comment]
It looks like .tiff might be the culprit. It doesn't break my browser but images appear to be broken. 
https://artsy-media-uploads.s3.amazonaws.com/ktwYLOQHLq8g3YX7-ilQrg%2FCCITT_1.TIF
