### ISSUE TITLE
Export data to redshift via fulcrum

### ISSUE THREAD

**Issue by alexanderfabry** [artsy/positron#415]
We sometimes have questions about articles, writers, etc, but right now the data isn't easily accessible. 

Via @joeyAghion: the pattern has been for apps to export CSVs of their data to an appropriately named subfolder of artsy-data/reports on S3. E.g., `artsy-data/reports/positron_articles/export_201506011208.csv` and for fulcrum to handle the schema and import.

**Comment by craigspaeth** [comment]
I believe Kana shipped this. Lmk if that's not the case.

**Comment by alexanderfabry** [comment]
Shipped but would be nice to add article body data to the export, which is missing currently.
