### ISSUE TITLE
No articles showing in top section?

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#420]
![screen shot 2015-06-02 at 1 13 14 pm](https://cloud.githubusercontent.com/assets/3196536/7942019/2b2ac03a-0929-11e5-931a-d3e887c0312a.png)

**Comment by kanaabe** [comment]
The top section is reserved for tier 1 articles, should there be a different criteria?

**Comment by craigspaeth** [comment]
Halley & I talked about being able to choose those explicitly. It's a todo, for now you just need to make some articles tier 1 under that article's admin tab.

**Comment by kanaabe** [comment]
Yup, here is that issue: https://github.com/artsy/positron/issues/394
Closing this one in favor of 394!
