### ISSUE TITLE
Hide Subscribe pop up when other subscribe forms are visible.

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#422]
Subscribe pop up should fade out at the bottom of the page / when the on page field is visible.

![screen shot 2015-06-02 at 1 16 45 pm](https://cloud.githubusercontent.com/assets/3196536/7942098/d4d8d11c-0929-11e5-8032-f2390eb8c894.png)

**Comment by kanaabe** [comment]
Closed in https://github.com/artsy/force/pull/2933
