### ISSUE TITLE
On article pages Subscribe pop up doesnt show until you scroll to bottom

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#423]
Only shows up when you are on the related articles.

![screen shot 2015-06-02 at 1 19 55 pm](https://cloud.githubusercontent.com/assets/3196536/7942147/2860ec48-092a-11e5-952d-3760f07ceba7.png)

**Comment by kanaabe** [comment]
It's set to pop up when it reaches 50% of that feed. It looks like it's working for me, can you try to add more articles to the feed?

**Comment by owendodd** [comment]
This is on articles not on the overview. Overview seems fine

**Comment by kanaabe** [comment]
Yup I mean the feed on the bottom of the article. 50% of the 'More From Gallery Insights' section.

**Comment by owendodd** [comment]
Ohhhhhh got it. Yeah, I actually intended it to show up while still on the article. And then disappear once you hit the bottom subscribe / related articles

**Comment by kanaabe** [comment]
Ah I see. I can fix that. So do we want it to pop back up again if they scroll back up?

**Comment by owendodd** [comment]
Yeah that would be great.

**Comment by owendodd** [comment]
Thanksss

**Comment by kanaabe** [comment]
Closed in https://github.com/artsy/force/pull/2933
