### ISSUE TITLE
Gallery Insights should pull from related articles when there are no featured.

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#424]
Also, headline should top align with images

![screen shot 2015-06-02 at 12 59 58 pm](https://cloud.githubusercontent.com/assets/3196536/7942206/c1d42a5c-092a-11e5-932e-16edd0a9d7ed.png)

**Comment by kanaabe** [comment]
Hm ok. So the header is not aligned because it's missing a slogan which I think was 'Information, insights, inspiration. Exclusively from Artsy' according to the comp.

As for related articles, should they pull from tier 1? Or the recent ones?

**Comment by owendodd** [comment]
Ahhh got it. Ok I just added the slogan. Tier 1 would be good for related.

**Comment by kanaabe** [comment]
Also, should we assume this property for any vertical that doesn't have enough featured_links?

**Comment by owendodd** [comment]
Yeah I think that's smart.
