### ISSUE TITLE
Gallery Insights vertical home displaying partnership copy on Martsy

### ISSUE THREAD

**Issue by rchlgss** [artsy/positron#427]
Should not have "in partnership with" at all
![screenshot_2015-06-02-13-02-51](https://cloud.githubusercontent.com/assets/12517187/7944340/fd00b7be-0937-11e5-9505-77ee104c9d69.png)

**Comment by kanaabe** [comment]
This is resolved, please check again!

**Comment by rchlgss** [comment]
You're right. Didn't refresh enough times! Thanks @kanaabe
