### ISSUE TITLE
Add schema.org metadata in preparation of Parsely trial

### ISSUE THREAD

**Issue by alexanderfabry** [artsy/positron#429]
See https://www.parsely.com/docs/integration/metadata/jsonld.html

Parsely needs some metadata about our articles to track and analyze performance.

Example:
```
<script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "NewsArticle",
        "headline": "Zipf's Law of the Internet: Explaining Online Behavior",
        "url": "http://blog.parsely.com/post/57821746552",
        "thumbnailUrl": "http://blog.parsely.com/inline_mra670hTvL1qz4rgp.png",
        "dateCreated": "2013-08-15T13:00:00Z",
        "articleSection": "Programming",
        "creator": ["Alan Alexander Milne"],
        "keywords": ["statistics","zipf","internet","behavior"]
      }
</script>
```

**Comment by craigspaeth** [comment]
@alexanderfabry I assume this needs to be embedded in the front-end Force page right?

**Comment by alexanderfabry** [comment]
Yup, Parsely needs be able to see it on the article page.

**Comment by craigspaeth** [comment]
Sweet! @jtotoole gonna assign to you. Feel free to ping me for help implementing or bounce it back. This should actually be a Force issue (wish there was an easy way to move issues across projects).

**Comment by jtotoole** [comment]
Moved to Force: https://github.com/artsy/force/issues/3092
