### ISSUE TITLE
Captions disappearing from some uploaded images

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#434]
Captions have disappeared from some uploaded images in the two articles below—sourcing more. 
https://www.artsy.net/article/artsy-editorial-venice-biennale-2015-21-top-museum-shows-events
https://www.artsy.net/article/artsy-editorial-at-the-venice-biennale-balancing-hope-with-national-interests

Notice that the ones in the second article are not _all_ missing. The general behavior for captions is to disappear if the caption field is engaged with after the initial session (can explain more if that's not clear).

**Comment by craigspaeth** [comment]
@halleyjohnson: You mentioned this happens when messing with the image module in the Writer edit UI right? Can you please log steps to reproduce this so we can try to track down the bug.

**Comment by halleyjohnson** [comment]
@craigspaeth I meant this could be related; no idea how exactly these disappeared, we just stumbled upon them. But the bug I am aware of happens this way:

Enter artwork caption.
Save draft or article.
Reopen article.
Engage with caption field.
Caption disappears upon engage.

There may be a time factor—I'm not sure that every time you reopen the article this happens, but may lapse after a while of not editing it.
