### ISSUE TITLE
Can convert a slideshow into sections

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#440]
Partners who want to clean up old posts need this feature + reordering sections.

**Comment by halleyjohnson** [comment]
@craigspaeth Is there any timeline for this? We are planning to reformat a bunch of old posts in the near future, and if this is in the works sooner than later we'll hold off for it. Let me know, thanks!

**Comment by craigspaeth** [comment]
Unfortunately it's not planned for this sprint, and I wouldn't count on next sprint either. If you want to reformat sooner than that I'd go for it now.

**Comment by halleyjohnson** [comment]
Understood. Thanks for context!

On Tue, Jul 7, 2015 at 3:37 PM, Craig Spaeth <notifications@github.com>
wrote:

> Unfortunately it's not planned for this sprint, and I wouldn't count on
> next sprint either. If you want to reformat sooner than that I'd go for it
> now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/positron/issues/440#issuecomment-119204163>.
>



-- 
Halley Johnson
Editorial Associate
Artsy <http://artsy.net/>  ⁄  401 Broadway, 25th Floor, New York, NY, 10013

halley@artsy.net

Artsy Editorial <https://artsy.net/posts/featured>
