### ISSUE TITLE
Need bullet lists in Artsy Writer to uniform text

### ISSUE THREAD

**Issue by ferberre** [artsy/positron#448]
https://files.slack.com/files-pri/T02531TU5-F06F3KRBK/slack_for_ios_upload.png

https://files.slack.com/files-pri/T02531TU5-F06F3ETTQ/text_not_uniform.png

**Comment by craigspaeth** [comment]
@kanaabe: This should just be a matter of configuring Scribe to allow `ul`s and `ol`s [here](https://github.com/artsy/positron/blob/master/client/apps/edit/components/section_text/index.coffee#L51) [here](https://github.com/artsy/positron/blob/master/client/apps/edit/components/section_text/index.coffee#L20) and [here](https://github.com/artsy/positron/blob/master/client/apps/edit/components/section_text/index.coffee#L84).

I'm imagining the icons should look like Gmail/Google Docs e.g.

![image](https://cloud.githubusercontent.com/assets/555859/8212604/83b5fd2e-14ea-11e5-965e-908387f7f685.png)

When you pick this up lemme know and I'd be happy to provide icon assets/happy if you want to build those yourself.
