### ISSUE TITLE
Admins should be able to set an article as "Featured" for Google News

### ISSUE THREAD

**Issue by broskoski** [artsy/positron#453]
This seems less important, but an option:

http://googlenewsblog.blogspot.com/2011/09/recognizing-publishers-standout-content.html

**TLDR;**
If you put the tag in the HTML header of one of your articles, Google News may show the article with a ‘Featured’ label on the Google News homepage and News Search results. The syntax for this new tag is as follows:

`<link rel="standout" href=“http://www.example.com/scoop_article_2.html” />`

**Comment by halleyjohnson** [comment]
@broskoski One thought is that we could collapse this with the "Tier 1" designation that's already in Writer, as that's a good indication that the article is important.

**Comment by broskoski** [comment]
@halleyjohnson good call! Closing this, will use the tier info to make the link.

**Comment by halleyjohnson** [comment]
@broskoski @craigspaeth I just wanted to follow up on this point: I think Tier 1/2 is a good way to indicate the importance of an article, and I think it would be best to keep this designation for that function as we move on to a more sophisticated method of selecting the posts that go at the top of the Magazine feed. Ie, we could separate Tier 1/2 from designating anything with regard to that section once we have a more manual ability to choose what goes up there.
