### ISSUE TITLE
Optimize individual article page load speed

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#455]
Should be eventually split into Force/MG stories...
- [ ] Compress image sizes on mobile for artworks and embedded images
- [x] Consider denormalizing artwork data so client-side fetching isn't necessary
- [x] Index articles by slug
- [ ] ...

**Comment by kanaabe** [comment]
On mobile, articles now have their own asset package: https://github.com/artsy/microgravity/pull/1009

Will look into the points ^
