### ISSUE TITLE
Exclude from google news

### ISSUE THREAD

**Issue by broskoski** [artsy/positron#457]
Add a flag to exclude an article from Google News. Might be worth it to add this as a query param as well, for generating sitemaps.

**Comment by craigspaeth** [comment]
Is this related to "paid content"? Should we indicate it as a `paid_content` field or be as specific as `exclude_from_google_news`. I imagine there might be other uses for a `paid_content` flag down the line, but being more explicit might be a safer way to go.

**Comment by broskoski** [comment]
Was only going off of Robert's last comment in that email thread: "Yes, subscriber posts. There could other reasons we would like to exclude articles so better to call the flag "Include/don't include in google news" as opposed to "subscriber post"." 

I have no opinion on what the attribute should be called :)

**Comment by craigspaeth** [comment]
:-P ah I missed that last part. Okee doke, lets do the explicit flag first and refactor/migrate later if need be.

**Comment by craigspaeth** [comment]
Closed via https://github.com/artsy/positron/pull/476
