### ISSUE TITLE
"What to Read Next" is pulling most recently edited, not most recently published

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#466]
![opening tonight in new york 20150713](https://cloud.githubusercontent.com/assets/10982707/8652574/a603bb42-297f-11e5-9804-1f79befe6e38.jpg)

Pretty much all the "X Artists Who Did X"-style posts in this list were published months/years ago and recently updated.

**Comment by craigspaeth** [comment]
Just need to add a `sort: '-published_at` [here](https://github.com/artsy/force/blob/master/models/article.coffee#L34). Technically Force issue.
