### ISSUE TITLE
Can hide vertical from public users

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#467]
Will be useful for test-driving verticals without giving users an access point via articles that are included in it (by clicking into the thumb bar that appears at the top of each article in the vertical). Just a toggle, like for feature pages, would be great.

**Comment by craigspaeth** [comment]
@halleyjohnson: Would it suffice to test that out on stagingwriter.artsy.net & staging.artsy.net? If that's too much of a pain happy to try and address this.

**Comment by halleyjohnson** [comment]
@craigspaeth Absolutely, didn't realize I could use this. Thanks for the tip.
