### ISSUE TITLE
Links don't play well with H3 text

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#468]
Pretty crowded in here. CC @nsimmons206 who may have some specific thoughts on a design fix here.

![screen shot 2015-07-13 at 17 35 13](https://cloud.githubusercontent.com/assets/10982707/8653634/aac1a134-2985-11e5-8b1e-09fc6c3a80e2.png)

**Comment by craigspaeth** [comment]
My hunch is we shouldn't be using H3s for longer body copy as caps case is generally hard to read in these cases. Would probably be more preferable to keep this in Garamond—maybe we can emphasize it in a different way. I wonder if we can introduce a feature in Writer to warn against this :bulb:.

Tangentially related—feels like we could also make a pass at cleaning up leading/spacing issues across articles.

**Comment by halleyjohnson** [comment]
Yes, agree on not using it for long body copy, but we have been using it in lieu of a better minimal text solution for features like this one:

https://www.artsy.net/article/artsy-editorial-15-must-see-booths-at-art-basel-2015

Either way, we will probably want to hyperlink H3 at some points and would be good to clean that up in general.

And totally agree on leading/spacing issues, we are pretty much feeling around in the dark on this one and just moving stuff around until it looks okay. I'm overdue on a couple of bugs here (teaching interns to log them today, hooray!) which are related to inconsistent spacing.

**Comment by craigspaeth** [comment]
:+1:
