### ISSUE TITLE
Can query for writer.artsy.net/api?exclude_google_news=true/false

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#478]
Should be the only thing left to make this happen https://github.com/artsy/force/issues/3173

**Comment by craigspaeth** [comment]
Probably just need to add the proper validation param here https://github.com/artsy/positron/blob/master/api/apps/articles/model.coffee#L86

**Comment by jorystiefel** [comment]
Look again @craig, I'd already added this ability in. WAY ahead of you!

**Comment by craigspaeth** [comment]
Waah, You read my mind!

![](http://i.imgur.com/s8JlpMN.gif)
