### ISSUE TITLE
Author not showing up on article pages

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#480]
for this author: https://www.artsy.net/margot-weller/articles

![screen shot 2015-07-22 at 11 21 01](https://cloud.githubusercontent.com/assets/10982707/8829281/c1c2a290-3063-11e5-8b01-10f4c2e29e0a.png)

Will look more to see if there are other examples, but @craigspaeth maybe this is related to you guys implementing organizations? If so I'll hold off till that's done and check it again.

**Comment by craigspaeth** [comment]
@halleyjohnson Doesn't have to do with organizations—definite bug.

**Comment by kanaabe** [comment]
Closing until another example appears. 

<img width="773" alt="2015-10-18_2003" src="https://cloud.githubusercontent.com/assets/2236794/10567446/561133bc-75d3-11e5-87ad-0206e2e0f32e.png">
