### ISSUE TITLE
Exclude all non-Artsy Editorial articles from Google News sitemap

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#486]
Instead of excluding individual articles from Google News, we should automatically exclude all articles not posted by Artsy Editorial.

In the future, it may be useful to be able to feature individual articles from other users to Google News, but this is less urgent.

**Comment by craigspaeth** [comment]
Technically this is a Force issue, and a simple matter of specifying `author_id` [here](https://github.com/artsy/force/blob/master/apps/sitemaps/routes.coffee#L13). @jtotoole or @kanaabe feel free to assign yourself or me this issue. First come first serve :D

**Comment by jtotoole** [comment]
I got it!
