### ISSUE TITLE
An admin can curate an overview page of "featured links" for a "BrandPartner"

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#490]
Moved Owen's comments to this issue https://github.com/artsy/force/issues/3316

> The main change to the current page will be the fact that the overview page will be a set of featured links rather than an automated feed of current / past shows. Each link will have a thumbnail, subheadline (describing the content type), headline, and desc (which will be used as either an author byline, date range, or location).

I can follow up with a comp for the Writer aspect of this, but basically we'll want to reuse generic admin UI to allow "10" featured links. You can reference how we do this in Verticals.

![image](https://cloud.githubusercontent.com/assets/555859/9445087/44ee9698-4a58-11e5-88d1-aee8f103f6e8.png)

So a `brand_partner_overview` API app that models the data something like...

```
{
  partner_id: ObjectId() // References gravity partner `_id` field
  featured_links: [
    {
      thumbnail_url: '',
      headline: '',
      subheadline: '',
      description: ''
    }
  ]
}
```

**Comment by alexanderfabry** [comment]
Should this story be in force?

I think we'll want a story in positron around managing the featured links for the BPP, though.

**Comment by owendodd** [comment]
@craigspaeth mentioned it would be better here. Maybe since the majority of the work will be around the featured links it seems. Happy to break stories out if there is a way that makes more sense though Craig!

**Comment by alexanderfabry** [comment]
Would personally find it clearer to have the work items broken out, since there's definitely stuff that needs to happen on Force, but happy to do whatever @craigspaeth and @kanaabe like best!

**Comment by craigspaeth** [comment]
:-P in my attempt to save you some time Owen, I've probably ended up causing us to spend more time discussing this. Sorry about that! I went ahead and broke up the issues https://github.com/artsy/force/issues/3316

**Comment by owendodd** [comment]
Haha, much appreciated Craig!
