### ISSUE TITLE
Enable tagging for better content organization

### ISSUE THREAD

**Issue by kevinhxiong** [artsy/positron#492]
Tags will become our primary tool for content segmentation. Important notes:
- Any piece can have multiple tags
- Not displayed on the front end (unless they're promoted to sections)
- Specific tags (e.g. Artsy City Guides, Reviews, News) can be promoted to "sections" on the site for visibility.
- Will power "What to Read Next" and other forms of related article discovery
- Best case scenario: tags are auto-populated with common misspellings and any Google News keywords we've already entered.

This issue expands on https://github.com/artsy/positron/issues/475.

**Comment by halleyjohnson** [comment]
@kevinhxiong I think the last point should be reversed—keywords should auto-populate from the tags we manually enter, based on the strategy we define around using keywords.

Would also like to add that if it's technically feasible to create an entry field for this on the Writer admin panel sooner than later, we have a bit of a slow few weeks and could prioritize tagging some of our backlog.

**Comment by kevinhxiong** [comment]
Thanks for the clarification, Halley!

**Comment by craigspaeth** [comment]
Change the UI from "keywords" -> "tags"

![image](https://cloud.githubusercontent.com/assets/555859/9738012/8c6577f6-5617-11e5-8f1f-c4996a645e87.png)
