### ISSUE TITLE
Crawl old articles to backfill author bylines

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#495]
Articles from the past year all have author bylines at the bottom of the page in the following format:

"—Firstname Lastname"

Articles until March-ish also have links to those authors' Artsy profiles.

If we can search article pages for these author tags and create a database with the results, I can clean up any errors so we can accurately auto-associate old articles to authors.

This can be done with a smaller select number of writers at first, if that helps with bandwidth.

**Comment by kanaabe** [comment]
@halleyjohnson 😭  2015!
