### ISSUE TITLE
Schedule posts

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#500]
Be able to schedule a post that is complete and set it to be live on a future date and time

**Comment by halleyjohnson** [comment]
As discussed in person—we should initially have some visual indication on the main feed of articles in Writer when a post is scheduled. Just a clear (maybe in a special color) note on the feed, like here:

![screen shot 2015-10-27 at 11 04 18](https://cloud.githubusercontent.com/assets/10982707/10762073/c8ec3508-7c9a-11e5-855f-76fd7ad4f459.png)

We can get fancier later, but this will help us keep track initially of what's scheduled and when.
