### ISSUE TITLE
bold text copied from Google docs is losing the bold formatting when pasted in Writer

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#504]
@kanaabe Related to the old formatting issues? I think this has been happening since the last deploy. It's any bolded text, whether italicized or not, this time.

**Comment by kanaabe** [comment]
https://github.com/artsy/scribe-plugin-sanitize-google-doc/pull/6

**Comment by halleyjohnson** [comment]
Hey Kana, this seems to still be happening, for bolded text whether italicized or not. I can share some example docs with you if that helps. Thanks!

**Comment by kanaabe** [comment]
Oh no, did Google Docs change something again? I can't keep up! I'll look into this, thanks.

**Comment by halleyjohnson** [comment]
Aaaaand again. We're losing italics when text is bolded and italicized. I can send over a google doc if this helps!
