### ISSUE TITLE
Author can select email specific thumbnail and headline in Writer

### ISSUE THREAD

**Issue by alexanderfabry** [artsy/positron#514]
These will be used to fill automatically generated editorial emails. Email design is identical to current format.

Selected thumbnail image should be available in either 640x480 or 276x196 sizing.

**Comment by owendodd** [comment]
You should also be able to add a credit long to correspond to the article thumbnail.

**Comment by halleyjohnson** [comment]
Note this should be an optional section (and could be only viewable to admins? not sure why an non-admin users would need to see this).

Could just be a checkbox ie "[  ] Prep this article for an email" on the Thumbnail panel, that opens a dropdown section with fields for image, headline, author, and credit line. I would suggest that these fields are autopopulated in the following way but that each can be overridden:

IMAGE: thumbnail image
HEADLINE: thumbnail headline
AUTHOR: *only* contributing author(s)
CREDIT LINE: _no autofill_

**Comment by sperle** [comment]
Probably the easiest way to handle the credit line would be to default to the article BUT allow for it to be overridden so wherever possible we can add a direct work link.

**Comment by halleyjohnson** [comment]
@kanaabe I'll give you more context on Sara's comment above when we chat tomorrow, then follow up with a takeaway here.
