### ISSUE TITLE
Share Button Test

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#519]
Three share button options to test evenly between our users. 

Option 1 = Current design.

Option 2 = Current plus fixed share buttons.

![screen shot 2015-09-24 at 6 24 30 pm](https://cloud.githubusercontent.com/assets/3196536/10088555/afc91cf0-62e9-11e5-9f8a-58b45e367cfa.png)

![screen shot 2015-09-24 at 6 28 28 pm](https://cloud.githubusercontent.com/assets/3196536/10088617/133ee77e-62ea-11e5-89da-fcaf2467d42e.png)

Option 3: Fixed share buttons only.

![screen shot 2015-09-24 at 6 35 46 pm](https://cloud.githubusercontent.com/assets/3196536/10088752/1dc929d8-62eb-11e5-8d1e-2e34be9c64e2.png)

![screen shot 2015-09-24 at 6 37 12 pm](https://cloud.githubusercontent.com/assets/3196536/10088781/5f555bb0-62eb-11e5-9512-f70776e57b1a.png)

and for infinite scroll articles:
![screen shot 2015-09-24 at 6 37 40 pm](https://cloud.githubusercontent.com/assets/3196536/10088792/6e517478-62eb-11e5-8bf4-34585ded66b6.png)

If it is possible we should run this test at the same time as: https://github.com/artsy/positron/issues/518

cc: @craigspaeth @kanaabe @alexanderfabry

**Comment by kanaabe** [comment]
Static Article | Infinite Scroll Article
-----------------|-------------------
Current | Current
Current + Fixed | Current + Fixed
Fixed Only | Fixed Only

So 6 possible outcomes, right? I'm also a little confused about option 3: could you elaborate a little more on "Buttons should stick and scroll up at the bottom of the article"
