### ISSUE TITLE
Slugs don't keep manual edits

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#526]
If you try to manually change the slug to something different that whatever it would normally first generate, it rarely sticks. This is the case when changing the slug on a draft and then saving it—which almost _never_ works, especially as the slug auto-updates if the title of the draft is changed, even if it's been manually altered before.

Here's an example of one I just published and had this problem with beyond the draft stage:

https://www.artsy.net/article/artsy-design-the-month-ahead-chicago-hosts-inaugural-architecture-biennial

I pushed "generate slug from title & author name" right before publishing, which should have produced (and showed on the backend) "artsy-design-the-month-ahead-chicago-hosts-inaugural-architecture-biennial-design-auctions-hit-london-l-a-and-chicago", but it reverted to its auto version when it published. I didn't save or change anything in between generating the slug and hitting publish.

Once the article is published, the slug usually freezes unless the piece is unpublished and republished, which opens the same can of worms. But I have had other team members say that they've edited a published article without unpublishing it and had the slug change.

**Comment by halleyjohnson** [comment]
Amendment: the article I linked above now has the extended slug—I opened it and re-generated it, then saved it.

**Comment by jtotoole** [comment]
@halleyjohnson Do we also want to adopt one of the new URL formats [discussed here](https://github.com/artsy/positron/issues/310)?

**Comment by halleyjohnson** [comment]
@jtotoole Kana and I chatted offline and think it's no big win to do them
with dates. They just need to stick when you change them!

On Mon, Oct 26, 2015 at 6:12 PM, jtotoole <notifications@github.com> wrote:

> @halleyjohnson <https://github.com/halleyjohnson> Do we also want to
> adopt one of the new URL formats discussed here
> <https://github.com/artsy/positron/issues/310>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/positron/issues/526#issuecomment-151299134>.
>



-- 
Halley Johnson
Editorial Associate
Artsy <http://artsy.net/>  ⁄  401 Broadway, 25th Floor, New York, NY, 10013

halley@artsy.net

Artsy Editorial <https://artsy.net/posts/featured>

**Comment by jtotoole** [comment]
:+1: , in that case will close https://github.com/artsy/positron/issues/310
