### ISSUE TITLE
Featured artworks aren't loading in admin panel and entering slug manually doesn't work

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#530]
We had logged this for artist names a while back, but I think it's worse for artwork pages.

This draft has multiple artworks in it and none of them are showing up in the featured section:
![screen shot 2015-10-09 at 17 45 54](https://cloud.githubusercontent.com/assets/10982707/10406395/a9c93306-6ead-11e5-8f33-64443ca8ebbe.png)

Entering the slug manually has never worked for artworks.

**Comment by kanaabe** [comment]
Ah I believe this is fixed, feel free to reopen if it isn't.
