### ISSUE TITLE
Add character limit to thumbnail_title

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#533]
Thoughts on truncating headlines that push down the header?

<img width="1183" alt="screen shot 2015-10-14 at 5 39 49 pm" src="https://cloud.githubusercontent.com/assets/3196536/10498910/5859feaa-729b-11e5-9ec4-51eedc3622dc.png">

cc @craigspaeth @halleyjohnson @alexanderfabry @kanaabe

**Comment by craigspaeth** [comment]
:+1:

**Comment by halleyjohnson** [comment]
Truncate how?

**Comment by owendodd** [comment]
@halleyjohnson I was imagining something like this.

![screen shot 2015-10-14 at 5 59 26 pm](https://cloud.githubusercontent.com/assets/3196536/10499282/60b3a5f4-729d-11e5-9bb4-4cd18a3fcf6a.png)

**Comment by halleyjohnson** [comment]
I think it's much better to put a max limit on the characters in that field than to cut off part of the title.

**Comment by owendodd** [comment]
That is just pulling the headline right now. But maybe the best thing would be a secondary short headline field?
