### ISSUE TITLE
Related articles should take into account associated fairs, auctions, and sections

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#536]
@kanaabe Just logging this so we don't forget.

**Comment by kanaabe** [comment]
I think the best way to approach this will be to create a new endpoint or be able to pass in a 'related' param that aggregates a bunch of articles including related tags, related artists, and ultimately the magazine feed if there are no relationships. There's a ton of fetching on the client side to populate this section in Force right now so it's probably ideal to just have it available on the API. Thoughts, @craigspaeth ?

**Comment by craigspaeth** [comment]
Yep :+1: I support an API level change. Something like `/api/articles?related_to_article_id=`

**Comment by owendodd** [comment]
closing for https://github.com/artsy/positron/issues/747
