### ISSUE TITLE
Google is pulling bylines into headlines for some articles

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#545]
Just have one example of this found accidentally, not sure yet what the pattern is, but it's this one:

https://www.artsy.net/article/artsy-editorial-15-must-see-booths-at-art-basel-2015

![screen_shot_2015-10-21_at_8 42 10_pm](https://cloud.githubusercontent.com/assets/10982707/10647120/ae553bda-7804-11e5-90e4-3ce5906bd7d7.png)

**Comment by eessex** [comment]
@halleyjohnson, have you seen any issues with this since the new meta panel went into action?

**Comment by halleyjohnson** [comment]
Nope, I think this is a super old issue.
