### ISSUE TITLE
Facebook and Twitter share buttons are picking up the URL from the top article on the infinite scroll feed

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#546]
Email button seems to be picking up the right URL, but all facebook and twitter share buttons (top, left, and bottom) of the articles below whatever is at the top of the infinite scroll page you're on, are pulling that top article's URL.

**Comment by jtotoole** [comment]
Closed (I think) via https://github.com/artsy/force/pull/3670 -- lemme know if there are any more issues!
