### ISSUE TITLE
Apple News is displaying bylines badly

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#548]
I think because of the way Artsy Editorial and the contributing authors are structured on our site, Apple News is picking them up as co-authors.

![screen shot 2015-10-27 at 17 55 53](https://cloud.githubusercontent.com/assets/10982707/10773827/123cbfe6-7cd4-11e5-910d-6e86f9b568d1.png)

![screen shot 2015-10-27 at 17 55 49](https://cloud.githubusercontent.com/assets/10982707/10773829/15079eee-7cd4-11e5-9469-e821b9178868.png)

It's not ideal, obviously, but it seems somewhat excusable for the moment if we could figure out how to get rid of the rogue comma at the end? That just makes it look obviously broken.

**Comment by jtotoole** [comment]
Closed via https://github.com/artsy/force/pull/3719

![img_2911](https://cloud.githubusercontent.com/assets/6501236/10955409/887ad8ca-8321-11e5-9bff-faf37894b041.PNG)
