### ISSUE TITLE
Footer Formating Isn't Sticking

### ISSUE THREAD

**Issue by isaac452** [artsy/positron#559]
Hey! Running into a bug when copy/pasting text from Google docs. The footers at the bottom of the post lose their ital footing, and sometimes when we change it manually the formatting is lost once the article is published.

Example of the wrong formatting if that's helpful:
![screen_shot_2015-10-23_at_17 53 24](https://cloud.githubusercontent.com/assets/13339955/10851236/52ca35ec-7f00-11e5-84b6-08d4740f2f46.png)

**Comment by halleyjohnson** [comment]
Some background on this guy over here: https://github.com/artsy/positron/issues/504

**Comment by craigspaeth** [comment]
Thanks @isaac452 & @halleyjohnson can you batch up some of the more important bugs into a bug bounty card in Trello.
