### ISSUE TITLE
Some dependencies complaining about peers / main.js unhappy

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#574]
Deployed about two hours ago when things looked fine locally, but was getting an infinite spinner on production. After attempting to re-install modules locally, i was getting some unmet peer dependencies when trying to `npm install` or `npm shrinkwrap --dev`. 

`simple-modal`:
![2015-11-11_2059](https://cloud.githubusercontent.com/assets/2236794/11091793/8160982c-88c1-11e5-9768-e53a14f9025b.png)
I switched back to @craigspaeth's [version](git://github.com/craigspaeth/simple-modal.git#e159c416840191b161aef83fd91366a73470488b)

`mongojs`:
I was able to get around `mongojs` by installing `kerberos`, issue looks the same [here](http://stackoverflow.com/questions/33642666/mongodb-kerberos-peer-dependency) 

After resolving these dependencies on install, i'm now getting major errors when I run the app locally. `main.js` is failing. Assuming it's related to the above even though the install is clean at this point. 

For now I rolled back (checkout `heroku releases` to see where I rolled back to). Seems like @jtotoole also rolled back to that release recently. I'll look over this again tomorrow, but just putting my findings here!

**Comment by craigspaeth** [comment]
Ack! For a moment there we added `npm install npm@latest` into the build, which would put Positron at npm 3... which has new behavior for peer dependencies. I wonder if this is the issue. One can debug by doing `npm i npm@latest` locally and attempting to reinstall node modules for Positron.

**Comment by kanaabe** [comment]
Yes! I read about the updates to peer dependencies, how they will warn instead of automatically install when there are peer conflicts. I am using npm 3 which is why I think it's more specific, a dependency level issue. Anyway, I'm going to try to resolve that today. Likely an issue with simple-modal like you mentioned. 

still getting this after running `npm i npm@latest` and reinstalling modules:
```
npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID jadeify@2.1.1 requires a peer of browserify@>= 2.4.0 < 4 but none was installed.
```

**Comment by craigspaeth** [comment]
Sorry, I realized I should have suggested this first--but since we're using npm 2 on the other projects I think it might actually be preferable to just run npm i npm@2 in the semaphore build and expire semaphore caches. We can deal with the peer dependencies thing when switching to npm 5 (soon when heroku and semaphore accept it). Ultimately thought I'm happy with either way. Good luck! Let me know if you get stumped and I am take a look.

**Comment by kanaabe** [comment]
Whoah spent all day on this, but we're now resolved and positron-production now matches master and I understand npm/versioning a LOT more. 

The issue was with browserify-dev-middleware. I reverted back to the version without locked dependencies and browserify was able to do its thing. I suspect that the browserify version it was trying to use in its package.json did not play nice with the browserify version that positron's package.json was trying to use. That's sounds like the kind of thing a package manager should be helping us catch though...It's a guess. Do you have any thoughts? 

That being said, I also used `npm i -g npm@2` as part of the build custom commands so positron should now be building with npm2. I removed it from the build command but that part should stay cached, right?
