### ISSUE TITLE
Preview links are routing to old articles in some drafts

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#586]
I think this is happening when you don't write a title fast enough and a generic slug is generated, then it gets conflated with an old article.

Example here (publishing Friday AM):
https://writer.artsy.net/articles/564ba19370b9500600777aa8/edit
preview links to https://www.artsy.net/article/artsy-editorial-11-17-15

**Comment by kanaabe** [comment]
Closing now that we have more granular time-based preview slugs
