### ISSUE TITLE
Superarticle management

### ISSUE THREAD

**Issue by alexanderfabry** [artsy/positron#587]
Superarticles contain:
- overview / intro section with headline and intro text
- normal article body sections + image / other modules
- new linked article modules, which are headlines and thumbnails at specific locations within the superarticle that link out to the respective other articles
- table of contents of the associated sub-articles
- custom footer to article with article table of contents
- custom header with dropdown table of contents on hover

Other updated components:
- embed functionality (will be used for interactive map)
- improved slideshow, ideally can be either artworks OR internally uploaded images, but can make do with uploaded images if necessary
- updated video embed module
- full-bleed video embed capabaility for overview / intro section (though good to be able to use static images for that too)

Clicking into sub-articles of the super-article (or even landing on subarticles via search / social / email) preserves the superarticle header and footer.

The UBS superarticle also has:
- partner logo
- external link to partner download app

See attached!

![ubs_eoy_desktop](https://cloud.githubusercontent.com/assets/598684/11357590/ae8310c2-9236-11e5-8293-6f5bd6d2218d.jpeg)

cc @owendodd @craigspaeth @kanaabe

**Comment by owendodd** [comment]
Thanks @alexanderfabry! Detailed spec coming tomorrow.

**Comment by craigspaeth** [comment]
Thanks @alexanderfabry ! @kanaabe let me know how I can be most useful here. I'm happy to build out the Writer api-side/super article admin side, article components like call-out or slideshow, front-end. Happy to tag team in w/e way is most efficient for you.

**Comment by owendodd** [comment]
Overview of the Super Article Admin. This approach splits the functionality into two groups which are controlled in different places. The first group contains the Article Header, Introduction, and Background Image. This can be activated in the Content panel by hovering over the topmost block add button (where we currently allow the addition of header images / videos). This functionality would not be limited just to super articles but could be used for a special feature of some sort (when used for outside of the context of a super article, we would maintain the normal artsy header, and wouldn't show the logos / custom header / or custom footer).

The second group of functionality is the real Super Article controls, and is controlled in the Admin panel. By enabling the super article, the full screen background would be enabled as well, and a user would have to revisit the Content panel to finish inputing the required. The admin panel also allows authors to upload partner logos, a partner link, and assign sub articles (the sub articles would then show up in the table of contents, and would all get the custom header). 

Hopefully this makes some sense. Happy to adjust if there are better ways to approach aspects of this. I'll split this up into the issues on the bus tomorrow.

![screen shot 2015-11-25 at 6 31 25 pm](https://cloud.githubusercontent.com/assets/3196536/11411839/d0152492-93a2-11e5-8617-9d0a924b4f39.png)

 

![artboard 8](https://cloud.githubusercontent.com/assets/3196536/11411733/4a594f64-93a1-11e5-94ae-c874862e1f10.jpg)

**Comment by owendodd** [comment]
cc @alexanderfabry @craigspaeth @kanaabe

**Comment by craigspaeth** [comment]
Awesome!! I like how this gives a Fullscreen Background block for any article! Very exciting to see these features and have you take over Writer design Owen!

One thing that isn't clear to me is how would I remove the fullscreen background section and go back to a normal article format once added? Currently article sections are removable via the hover controls, but I don't know what the hover controls would look like in this case. Assuming they don't appear at all, there probably needs to be a "X REMOVE FULL SCREEN BACKGROUND" button somewhere.

:clap: :confetti_ball: :grinning: Thanks for putting this together! Looks great! Happy Thanksgiving!

**Comment by owendodd** [comment]
@craigspaeth Good catch :) will update shortly  
🎉🍸🎉

**Comment by kanaabe** [comment]
@owendodd Are super articles Artsy-admin only? Even the fullscreen background?

**Comment by owendodd** [comment]
@kanaabe Yeah, just checked with halley and seems like it should all be admin only

**Comment by owendodd** [comment]
@craigspaeth @kanaabe updated the admin comps so that you can delete the full screen background mod. 

![artboard 8](https://cloud.githubusercontent.com/assets/3196536/11479500/4cd9d39a-9760-11e5-9058-d1be8b617bd8.jpg)

**Comment by kanaabe** [comment]
Closing in favor of smaller issues
