### ISSUE TITLE
SuperArticle Background

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#591]
SuperArticles should have a background image or video that fills the browser, there should be some resolution requirements for this asset. (~2460x1440px)

![screen shot 2015-12-02 at 2 55 46 pm](https://cloud.githubusercontent.com/assets/3196536/11542322/d68aa7f4-9904-11e5-8194-2d68fe566b4b.png)

**Comment by owendodd** [comment]
This is controlled in the Content panel of an article:

<img width="865" alt="screen shot 2015-11-26 at 10 51 02 am" src="https://cloud.githubusercontent.com/assets/3196536/11426751/3010c516-942c-11e5-938c-050a324908a0.png">
<img width="863" alt="screen shot 2015-11-26 at 10 51 15 am" src="https://cloud.githubusercontent.com/assets/3196536/11426753/308b2626-942c-11e5-8743-9c1cc06066f7.png">
<img width="864" alt="screen shot 2015-11-26 at 10 52 05 am" src="https://cloud.githubusercontent.com/assets/3196536/11426752/3088b968-942c-11e5-916c-ea856667a474.png">

**Comment by owendodd** [comment]
This is what this would look like when just the full screen background is being used, outside the context of a super article (here is the front end: https://github.com/artsy/force/issues/3816):

![screen shot 2015-11-30 at 4 58 00 pm](https://cloud.githubusercontent.com/assets/3196536/11485919/d0e2c566-9783-11e5-8cc2-07bf2b0a782f.png)
![screen shot 2015-11-30 at 4 58 22 pm](https://cloud.githubusercontent.com/assets/3196536/11485918/d0e3bb2e-9783-11e5-8104-ea225d7d3ef6.png)

**Comment by kanaabe** [comment]
hey @owendodd -- could I get an SVG icon for the Fullscreen Background option when you get a chance?

**Comment by owendodd** [comment]
Here you go!

http://cl.ly/3t301V0l1F1N

**Comment by kanaabe** [comment]
thank you!!! :star:
