### ISSUE TITLE
Super Article Logo(s)

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#592]
Super Articles should always have the full Artsy logo, and can optionally have a second logo for partnerships. This logo should be scaled to a max height of 80px and max width of 200px. 

![screen shot 2015-11-24 at 6 45 54 pm](https://cloud.githubusercontent.com/assets/3196536/11384171/a009fbb4-92db-11e5-9185-09b91389dfd8.png)

![screen shot 2015-12-02 at 2 36 35 pm](https://cloud.githubusercontent.com/assets/3196536/11542346/fa05b69c-9904-11e5-94cd-6f0999ca33f4.png)

<img width="649" alt="screen shot 2015-11-29 at 6 55 12 pm" src="https://cloud.githubusercontent.com/assets/3196536/11461269/96cb4436-96cd-11e5-96e5-e3b2b6461bb0.png">

**Comment by owendodd** [comment]
This is controlled in the Admin panel of an article:

<img width="862" alt="screen shot 2015-11-26 at 10 33 47 am" src="https://cloud.githubusercontent.com/assets/3196536/11426784/5118f4d6-942c-11e5-8d6b-25b3fa4c5027.png">
<img width="863" alt="screen shot 2015-11-26 at 10 37 08 am" src="https://cloud.githubusercontent.com/assets/3196536/11426785/511ba8e8-942c-11e5-908f-ade02c12a30a.png">

**Comment by owendodd** [comment]
Updated slightly. (2 additional fields)

![screen shot 2015-12-02 at 2 36 11 pm](https://cloud.githubusercontent.com/assets/3196536/11542339/f1d55a54-9904-11e5-9d13-5d7596330806.png)

**Comment by owendodd** [comment]
Also should note that I have been imagining partner logo 1 as an svg so we can use it in white/black. can we currently do that?

**Comment by zamiang** [comment]
Should the secondary partner logo also have a link?

**Comment by owendodd** [comment]
:)

**Comment by owendodd** [comment]
haha, they should actually both have links as I think the partner logo would link to somewhere different than the partner link.... so many fields!

**Comment by owendodd** [comment]
Ok this should actually be all the fields. It would be nice if we could hide these until you hit the 'Enable' toggle.

![screen shot 2015-12-02 at 3 59 50 pm](https://cloud.githubusercontent.com/assets/3196536/11544121/29f94694-990e-11e5-8a13-937d81774e70.png)
