### ISSUE TITLE
Super Article exit/entry point

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#594]
The article section of a super article should have the ability to add links to other articles. These links would display the Article thumbnail, thumbnail title, and a "Read Full Article" line.

<img width="1018" alt="screen shot 2015-11-29 at 6 15 06 pm" src="https://cloud.githubusercontent.com/assets/3196536/11460924/6e199644-96c5-11e5-93cf-9f95c1063f0c.png">

**Comment by craigspaeth** [comment]
Talked about this at standup today. This section in Writer, data-model-wise, should look like:

```
sections: [
  { type: 'article_callout', id: ObjectId('some-article-id'), title: '...', slug: '...', thumbnail_url: '' }
]
```

We can start with something that simple and denormalize `title`, `slug`, `thumbnail_url`. Then Alexxa mentioned wanting to ability to potentially customize the title or thumbnail—which we can potentially swap denormalizing for UI controls in a v2.

@owendodd: I think we'll want a design for the UI controls in Writer.

**Comment by owendodd** [comment]
OK this is what I'm thinking re: UI controls

This way you could use it for a plain text call out that functions as a pull quote as well. 

<img width="746" alt="screen shot 2015-12-07 at 9 19 52 pm" src="https://cloud.githubusercontent.com/assets/3196536/11646124/9542639a-9d28-11e5-85ed-af1c2985e10b.png">

<img width="756" alt="screen shot 2015-12-07 at 9 27 19 pm" src="https://cloud.githubusercontent.com/assets/3196536/11646184/66228206-9d29-11e5-8bec-693d6e5b4423.png">

**Comment by owendodd** [comment]
cc @craigspaeth @kanaabe @zamiang

**Comment by owendodd** [comment]
Also worth noting, I made some sizing adjustments to the 'insert' toolbar to maintain the single row. everything just got a little smaller / tighter.

<img width="637" alt="screen shot 2015-12-07 at 9 35 22 pm" src="https://cloud.githubusercontent.com/assets/3196536/11646353/3ad37a86-9d2b-11e5-822a-b0764286ee40.png">
<img width="671" alt="screen shot 2015-12-07 at 9 38 00 pm" src="https://cloud.githubusercontent.com/assets/3196536/11646354/3b11a0fe-9d2b-11e5-836e-f7af2f803dd4.png">
<img width="643" alt="screen shot 2015-12-07 at 9 40 43 pm" src="https://cloud.githubusercontent.com/assets/3196536/11646355/3b11eb54-9d2b-11e5-9e47-1b817600b850.png">

**Comment by craigspaeth** [comment]
:clap: nice work Owen! Thanks!

**Comment by craigspaeth** [comment]
Minor adjustment idea @owendodd , lmk what you think.

![image](https://cloud.githubusercontent.com/assets/555859/11659379/0206f55a-9d96-11e5-972c-0560c8754346.png)

* Clicking the callout would create the callout floated to the side (or the placeholder "Add callout text") and put the edit controls over it, to make things jump around less.
* Hovering over the text sections would only show the ( + ) controls above and below the callout to avoid nasty states
* Hoevering over the callout would only show the ( x ) remove control

**Comment by owendodd** [comment]
Yeah I think that makes sense to float it to the right. And yeah I agree that we shouldn't let you insert another content block next to the callout. 

Here is some slightly better comps :)

<img width="840" alt="screen shot 2015-12-08 at 10 55 20 am" src="https://cloud.githubusercontent.com/assets/3196536/11660337/bf23178c-9d9a-11e5-8f2a-defe36b1f9ea.png">

Article input:
<img width="824" alt="screen shot 2015-12-08 at 10 55 31 am" src="https://cloud.githubusercontent.com/assets/3196536/11660335/bf2161ee-9d9a-11e5-9ce3-3d9210a54c10.png">


Used for pull quote: 
<img width="847" alt="screen shot 2015-12-08 at 10 55 45 am" src="https://cloud.githubusercontent.com/assets/3196536/11660336/bf21e42a-9d9a-11e5-86ac-713c750ea0d6.png">

**Comment by kanaabe** [comment]
I love the dual purpose of linking an article and using it for a pull-quote. Great idea @owendodd
