### ISSUE TITLE
New Slideshow module

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#598]
Ability to add a slideshow into an article (limit to 10 images)

![screen shot 2015-11-24 at 7 16 33 pm](https://cloud.githubusercontent.com/assets/3196536/11384705/13619078-92e0-11e5-99e8-8ca91454f45d.png)

**Comment by owendodd** [comment]
Ok here is the real admin / front end for this guy. Let me know if you guys have input on the admin component, I tried to wrap it into the existing image module but maybe that isn't the best approach..


So starts off normal except here Image has been changed to Images:
<img width="887" alt="screen shot 2015-12-08 at 4 48 40 pm" src="https://cloud.githubusercontent.com/assets/3196536/11669752/497c7fa0-9dcc-11e5-996c-1abdd54cbc58.png">

First view here is normal as well. Add an image like you usually would (except adding an image wouldn't automatically close this module as it does now):
<img width="886" alt="screen shot 2015-12-08 at 4 48 53 pm" src="https://cloud.githubusercontent.com/assets/3196536/11669769/56bdec58-9dcc-11e5-8d85-900aac7a0503.png">


After adding though there is another button at the bottom to "Create a slideshow"
<img width="884" alt="screen shot 2015-12-08 at 4 49 07 pm" src="https://cloud.githubusercontent.com/assets/3196536/11669782/690bf9c2-9dcc-11e5-950f-5069ba8f3ba2.png">

Which, if pressed, switches to this mode where you could add additional images / edit captions:
<img width="887" alt="screen shot 2015-12-08 at 4 49 24 pm" src="https://cloud.githubusercontent.com/assets/3196536/11669845/d551b176-9dcc-11e5-9f51-f8cc641da42a.png">


Hitting the add button would take you to an empty state to add another image:
<img width="885" alt="screen shot 2015-12-08 at 4 49 38 pm" src="https://cloud.githubusercontent.com/assets/3196536/11669877/f073a0d6-9dcc-11e5-998d-ecad0bbc4bbf.png">

And then you can just keep doing this (here you can see the little hover to delete images):
<img width="801" alt="screen shot 2015-12-08 at 4 56 27 pm" src="https://cloud.githubusercontent.com/assets/3196536/11669890/01249dcc-9dcd-11e5-979f-f7fd8b6c151a.png">

I was thinking that you could scroll horizontally if there were too many images. Also dragging to reorder would be awesome if possible but not crucial.

Anyways, that's where this is at, lmk your thoughts.

**Comment by craigspaeth** [comment]
@owendodd I like it! I wasn't thinking of the slideshow as a part of images at first, but it makes total sense!

That sparked up an alternative idea (sorry if I'm being an annoying here)—what if we thought of the slideshow as another "layout" of the images section. Closer to how the artworks section functions, here's a really ugly + quick sketch of what I mean by this:

![images](https://cloud.githubusercontent.com/assets/555859/11672146/e0c27e28-9ddb-11e5-8ce0-cbf353064dcd.png)

One advantage is more screen real-estate for that top header part and it could also easily support converting between say a slideshow and a ["fillwidth"](https://cloud.githubusercontent.com/assets/555859/11672202/65400abc-9ddc-11e5-8f53-092c8de7c2eb.png) layout. (The fillwidth layout for images is something editorial definitely has wanted for a while too).

**Comment by owendodd** [comment]
@craigspaeth Great idea, will update tomorrow am!

**Comment by kanaabe** [comment]
Ok to close this?

**Comment by owendodd** [comment]
👌
