### ISSUE TITLE
New video embed

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#600]
Ability to embed video's at larger width's into articles with either a white Bg or a full width black bg. 

![screen shot 2015-11-24 at 7 23 36 pm](https://cloud.githubusercontent.com/assets/3196536/11384788/e453bf8a-92e0-11e5-89bc-f052136a0aa6.png)

**Comment by zamiang** [comment]
Looks like we just need a black / white checkmark or radio button in the video UI

**Comment by owendodd** [comment]
Yeah, would be nice if we can get them to display at a larger size too, currently i think videos are restricted to the width of the text

**Comment by kanaabe** [comment]
Ah yeah sorry I misspoke @zamiang - thought the video did bleed a little but it was the hero video that did that.
