### ISSUE TITLE
Query for all articles apart of super article

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#604]
Following up on our chat, I think it might be most useful and still a little more REST-kosher to add an endpoint to the root articles route that returns all of the articles that are a part of the super article. It should act something like this:

```
GET /api/articles?super_article_family_for=<Any of the following article IDs>
=> Returns...
[
  { is_super_article: true, title: 'The Year in Art' ... },
  { is_super_article: false, title: 'Top 20 Living Artists Today' ... },
  { is_super_article: false, title: 'The 20 Top Emerging Artists' ... },
  { is_super_article: false, title: '...t' ... },
  { is_super_article: false, title: '...' ... },
  { is_super_article: false, title: '...' ... }
]
```

That would involve some fancy query building like we [do for `all_by_author`](https://github.com/artsy/positron/blob/master/api/apps/articles/model.coffee#L168). Maybe something like...

````coffeescript
query.$or ?= []
query.$or.push {...}, {...} if input.all_by_author
query.$or.push(
  { _id: ObjectId(input.super_article_family_for) }
  { 'super_article.related_articles': ObjectId(input.super_article_family_for) }
) if input.super_article_family_for
````

@zamiang @kanaabe

**Comment by kanaabe** [comment]
Super :muscle: Family :family:

**Comment by zamiang** [comment]
@kanaabe mind if I take this one? Curious about adding to the positron backend.

**Comment by zamiang** [comment]
@craigspaeth I don't really see a good way to get the whole super family without multiple queries. But! Do have an idea that is kinda the…family spirit.

```
query.$or.push(
  { _id: ObjectId(input.super_article_family_for) }
  { 'super_article.related_articles': ObjectId(input.super_article_family_for) }
```
Will return the searched for article (via _id) and any super articles with the searched article as a related article.

Once we have that super article, we can go and fetch each individual article -- but that would have to be another query.

Personally, I feel like we should just go with 
```
query.$or.push(
  { 'super_article.related_articles': ObjectId(input.super_article_for) }
```
And then have clients fetch the related articles by passing all of the related articles in one query. Perhaps adding `ids` (an array of ids) to the `inputSchema`.

**Comment by craigspaeth** [comment]
I'm fine with either way, but joining multiple queries on the Positron side is going to be a lot faster, and maybe easier (at least definitely for the client), than doing it on the client's side via HTTP. I don't see any thing wrong with multiple queries on the Positron side, but it does make the code not a straightforward as I initially specced out. I encourage giving the multiple queries in Positron a try but happy with the other way if it proves too difficult.
