### ISSUE TITLE
Can't add links to images in Writer

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#615]
The little link modal doesn't want staying open

![screen recording 2015-12-08 at 04 00 pm](https://cloud.githubusercontent.com/assets/3196536/11669998/8977c5f0-9dcd-11e5-9372-c7e9dba09687.gif)

**Comment by kanaabe** [comment]
Seems to have something to do with this: https://github.com/ePages-de/scribe-plugin-enhanced-link-tooltip/commit/1d448f908f35eecec63d082b16cd6c727861b579

`mouseup` event is what's causing the tooltip to go away. I think we just need to update. The tooltip works if you use a trackpad. I'll come back to this.
