### ISSUE TITLE
Articles with banner images display a weird giant gap up top if your window size is too small

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#633]
Articles with banner images (large format images above the headline) display a weird giant gap up top if your window size is too small

examples:

https://www.artsy.net/article/artsy-editorial-16-emerging-artists-to-watch-in-2016
https://www.artsy.net/article/artsy-editorial-30-emerging-artists-to-watch-during-frieze-week

![screen shot 2015-12-16 at 15 26 46](https://cloud.githubusercontent.com/assets/10982707/11853085/f440333a-a409-11e5-977e-5f22e05fa1e4.png)

**Comment by kanaabe** [comment]
Closing in favor of https://github.com/artsy/force/issues/4023
