### ISSUE TITLE
Callouts show "Read full article" when no article is linked

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#638]
and subsequently 404

<img width="556" alt="screen shot 2015-12-21 at 11 01 44 pm" src="https://cloud.githubusercontent.com/assets/3196536/11948974/50c6e6ea-a837-11e5-82cc-dc2aa03341ad.png">

**Comment by owendodd** [comment]
Also seems like there is something happening related to this https://github.com/artsy/force/issues/3994

**Comment by halleyjohnson** [comment]
Seconded! This popped up after I published the article screenshotted above, when I first published it on Sunday night it was all good

**Comment by kanaabe** [comment]
Fixed and deployed! https://github.com/artsy/force/pull/4014/files
