### ISSUE TITLE
Get rid of Brands in writer

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#666]
![screen shot 2016-02-03 at 1 48 34 pm](https://cloud.githubusercontent.com/assets/3196536/12793145/15aa7eba-ca7d-11e5-982a-5acd28b4264f.png)

thoughts? cc @alexanderfabry @halleyjohnson

**Comment by craigspaeth** [comment]
:+1: We can always dig up deleted code thanks to git. IMO we should never keep something around if the only reason is because "we might need to bring it back later".
