### ISSUE TITLE
Show search should use v1 or investigate Google search issues

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#682]
Ryan is having a lot of problems waiting for shows to be indexed by Google which is what v2 uses for search. Instead, we should just try to find the show by slug via v1 or dive into Google's indexing and see if we can make any improvements there.

**Comment by owendodd** [comment]
I don't have full context here / this might be what you are saying, but would just pasting in a show slug/url like we do for artists work here instead of searching?

**Comment by kanaabe** [comment]
Yep, that's the idea! 

Though we use v2 in other places too like partners and fairs and it doesn't seem to be a problem for those entities so maybe that's worth investigating on the Google indexing side.

**Comment by owendodd** [comment]
Gotcha, thanks for clarifying!
