### ISSUE TITLE
Module picker updates

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#692]
Two new modules + slight rearrangement. When the two new modules don't display (for non-admin) the remaining 6 modules should expand to 3 columns two rows.

![screen shot 2016-03-27 at 5 42 35 pm](https://cloud.githubusercontent.com/assets/3196536/14067982/54b3a268-f443-11e5-86ce-6896ea27cccc.png)

Non Admin:
![screen shot 2016-03-27 at 5 37 13 pm](https://cloud.githubusercontent.com/assets/3196536/14067968/9dc7a09a-f442-11e5-9294-eace6876f517.png)

SVGs http://cl.ly/1X3P093K0d0e

**Comment by kanaabe** [comment]
non-Admin: 4x1 only text, artworks, video, images
Admin: 3x2 all options - TOC and Image set (second image)
Admin + Editorial Team: 4x2 all options (first image)

cc @owendodd lmk if that seems right to you

**Comment by owendodd** [comment]
@kanaabe yeah that seems perfect. Thanks!
