### ISSUE TITLE
Top Stories Callout component

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#710]
Be able to add a top stories callout that will show top stories from Parsely.

**Comment by kanaabe** [comment]
@owendodd Can I get a SVG for this when you have a chance?

**Comment by owendodd** [comment]
@kanaabe what do you think of wrapping it into the existing callout module and just doing a checkbox like this?

![desktop hd copy 14](https://cloud.githubusercontent.com/assets/3196536/14413498/0a901f38-ff4a-11e5-98e4-dc3761a0d1fc.png)

If you have another approach that is easer feel free to do that too. Here is the svg!

http://cl.ly/0v2d0B300o41

**Comment by kanaabe** [comment]
v. true. this is easier for me too! 👍

**Comment by owendodd** [comment]
👌
