### ISSUE TITLE
Remove Embedly cropping

### ISSUE THREAD

**Issue by dzucconi** [artsy/positron#723]
https://github.com/artsy/positron/blob/6c5b38b4d9c8b597c52efc835c95ec0c0785ea55/api/apps/articles/model/save.coffee#L266

`crop` shows up in a few places:

Places where it's used for displaying images within Positron's UI can move over to using Gemini: https://github.com/artsy/force/blob/master/components/resizer/services/gemini.coffee

It looks like we're returning pre-sized URLs through the API for Article#thumbnail_url: ![](http://static.damonzucconi.com/_capture/tY9g1HQ3Z7.png)

I'm not sure the reasoning here but these should be bare URLs that resolve to some un-proxied object on S3.

**Comment by kanaabe** [comment]
thanks @dzucconi, i'm working on this now. the weird thumbnail save is for Sailthru, not on regular thumbnails in the article. They need different size versions of the images they upload -- is there a better way we can handle this?

**Comment by dzucconi** [comment]
Pre-process a version you need in Gemini or resize it on the client, using Gemini's proxy. (Though I don't really know what Sailthru is)
