### ISSUE TITLE
Related content module missing between first two articles for repeat traffic

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#731]
Looks like the related content module between the first two articles (where external users would see the new email signup) has gone rogue:

![screen shot 2016-05-11 at 08 56 01](https://cloud.githubusercontent.com/assets/10982707/15181633/5560d326-1756-11e6-9c22-74c344d8ba34.jpg)

**Comment by kanaabe** [comment]
Closing in favor of general QA card: https://github.com/artsy/force/issues/4980. Feel free to add anything else you notice on that issue @halleyjohnson and thanks for spotting this!
