### ISSUE TITLE
Investigate Apple News

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#733]
All of our stories in apple news are a week old, is there maybe some issue with the rss feed that we are using for that?

**Comment by kanaabe** [comment]
Pretty sure I fixed this one of the recent PRs related to RSS feeds but I'll leave it to you to move to Done if you think it is.

**Comment by owendodd** [comment]
Seems like the feed is being updated now but there are a few other issues I noticed. First there is some weird byline stuff happening with a few articles. 

![img_0696](https://cloud.githubusercontent.com/assets/3196536/15477458/efeaa776-20d1-11e6-80b9-d90519567953.jpg)
![img_0697](https://cloud.githubusercontent.com/assets/3196536/15477460/f0056a7a-20d1-11e6-8ad2-226fadfcffec.jpg)
![img_0698](https://cloud.githubusercontent.com/assets/3196536/15477459/effcd978-20d1-11e6-905e-1e131ca2dd46.jpg)


The bigger issue is that our content isn't showing up in any of the explore feeds. Even once you drill down to topics like Fine Arts or Museums, there is still nothing. Lots of content from artnet, artnews, artinfo etc though. Do we have any control over how our content is being tagged for these channels?

**Comment by kanaabe** [comment]
I see -- yeah definitely happy to investigate that + fix the bylines. Moving back to In Progress.

**Comment by kanaabe** [comment]
Bylines are fixed going forward now. 

From Apple about Explore: 
With regards to your second question about the Explore resources: These resources are based on a combination of fairly complex algorithms and editorial selection. Once we’ve gotten you access to your account again, I’ll do some further research into whether there’s optimizing we can do to get Artsy higher in the results. 

I imagine it will take some tweaking with tags but I'll wait to see her recommendations.

**Comment by owendodd** [comment]
OK that all makes sense. I'll add a future card for converting to apple news. I wonder if it is something we could group with AMP. 

https://github.com/artsy/positron/issues/755

Will close this for now though
