### ISSUE TITLE
Restructuring Writer

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#743]
As a foundation to some upcoming differentiation projects, we can restructure writer to be more tailored to each user groups needs.

The new structure would be less user centric and more similar to cms. Instead of each user having an individual account, their login would grant them access to a 'channel'. There are 4 types of channels, the channel a user is in dictates where the content they publish lives, how it is visually treated, and the functionality they have access to.

_Channel Type Overview_

**1– Editorial**
This will stay essentially the same as it is now. They editorial channel posts articles to the Magazine feed, and has access to all writer functionality. There is only one of this channel type.

Users: Current Editorial users
Number of channels: 1
Writer Functionality Restrictions: None
Homepage: Magazine feed
Article view: same as now
Article related content: only editorial content
Linked from: Artist pages, artwork pages, gallery pages, auction pages, fair pages, show pages, homepage
Sections: Yes (future project)

**2– Team** 
This channel type will be used for the Life at Artsy blog, Gallery Insights, and Artsy for Education. Each of these channels will live as part of a separate page on a subdomain. Something like this: http://cl.ly/3p0Y3U3e3M0i, as you can see there would also be other components to these pages (for GI for example, we would connect the 'Artsy for Galleries' page under the same header. For LAB we would connect the jobs page under the same header, along with others). There is one tricky thing here with regards to Artsy for Education content, which we sometimes want to live under the editorial umbrella, but still be linked to from the Artsy for Education channel.

Users: Remy, Elena, Rachel, Jessica, Liz, more tbd.
Number of channels: 3 (Gallery Insights, Life at Artsy, Artsy for Education)
Writer Functionality Restrictions: No super articles, no fullscreen header, no header image / video, no toc, no jump links.
Homepage: Micro sites
Article view: same as now under microsite header
Article related content: only specific channel content
Articles linked from: channel microsite, editorial homepage (only for some Artsy for Education content).
Sections: Yes (future project)

**3– Partner**
Each parter will have a channel associated with their partner account. Anyone who has access to their gallery in CMS will be able to use the same login to access their writer channel. The contents posted through their channel would show up under the article section of their gallery profile page. (e.g. http://cl.ly/3M1U1D390t2S). Most partner channels would only be able to post to their own profile page. 

Users: Anyone that has a CMS login
Number of channels: As	many as we have gallery / institutional partners
Writer Functionality Restrictions: No super articles, no fullscreen header, no header image / video, no toc, no jump links, no callouts, no embeds, no image sets
Homepage: Gallery / institution profile page
Article view: same as now under the GPP or IPP header
Article related content: only content from that specific partner
Linked from: GPP or IPP
Sections: no

**4- Partner Support**
These channels are tailored for content that the Artsy team produces for our partners. Three examples of this are Ryan (gallery content), Collin (auctions content), and the content that we produce for fairs (mostly to highlight fair programming). The complicated thing about these channels is that there are only 3, but each channel posts to a number of places (depending on the partner that it is written for). Design for this will follow shortly

Users: Collin, Ryan, Morgan, more TBD
Number of channels: 3
Writer Functionality Restrictions: No super articles, no fullscreen header, no header image / video, no toc, no jump links, no callouts, no embeds, no image sets
Homepage: None
Article view: embedded into a fair microsite or w/ a partner specific header. 
Article related content: only content from that specific partner
Linked from: GPP, IPP, Auction page, fair microsite.
Sections: no

--- 

I'm sure there are some aspects of this that still need a little fine tuning, so feel free to raise any questions as they come up.

**Comment by owendodd** [comment]
@halleyjohnson @kanaabe how does this look to you guys?

**Comment by halleyjohnson** [comment]
Looks very thorough and accurate to me, @owendodd ! Thanks for spelling this out.

**Comment by owendodd** [comment]
@halleyjohnson @kanaabe here is another sketch, same thing just in a more visual manner. 

![v](https://cloud.githubusercontent.com/assets/3196536/15718705/a8320836-27fa-11e6-8beb-108705708f40.jpg)

@craigspaeth would be great to get some input from you here if you get the chance. I think it will be a pretty significant overhaul. @kanaabe may have followed up with you already 

😄

**Comment by craigspaeth** [comment]
I remember what this was reminding me of now! https://github.com/artsy/positron/issues/168 Very exciting stuff, looking forward to seeing this take effect piece-by-piece.
