### ISSUE TITLE
Google AMP

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#746]
We should capitalize on the ability to put our articles into this format to better surface them in Mobile. This would likely help improve Mobile usage, and it has its own tracking/analytics integration within GA.

The main KPI is more exposure in Mobile: https://www.ampproject.org/docs/reference/spec.html

More info here: https://support.google.com/webmasters/answer/6340290?hl=en

Ideally this would be launched for all article pages, but if it's easier to pilot on test group let's do that first. I tried to convert all this info into the checklist below, hopefully it helps!

**Comment by kanaabe** [comment]
Parsely tracking: https://www.parsely.com/docs/integration/tracking/google-amp.html?mkt_tok=3RkMMJWWfF9wsRonsqzPZKXonjHpfsX56egvWKSxlMI%2F0ER3fOvrPUfGjI4DTspmI%2BSLDwEYGJlv6SgFSbHBMaVi2LgPXhQ%3D
