### ISSUE TITLE
positron report export failing causing bad analytics

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/positron#770]
I can't speak to specifics here but maybe @wrgoldstein or @kanaabe can. The issue was identified when we noticed that the number of times partner_id's would appear in the report would change back and forth between the same two numbers. Kana mentioned she got as far as identifying the problem in positron as  an incomplete export.

This affects all positron analytics I would imagine, but specifically for the GR team there is no way for us to let them know in an automated way that their gallery has been featured on Artsy. So

**Comment by kanaabe** [comment]
Found some old data that had corrupted dates + fixed them. Uploads should be ok now. @nicholassewitz -- please check back in a couple days to ensure it's accurate.

**Comment by nicholassewitz** [comment]
WOHOOOO!

**Comment by nicholassewitz** [comment]
Seems like this is still not working properly due to an export size limit? or something along those lines. Took a look at reports from july 13th and 14th. The report on the 14th stopped exporting at around ~16000 rows, but the 13th went beyond.
