### ISSUE TITLE
SEO Tool

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#798]
New SEO tool for writer. There is an icon/button that lives fixed in the bottom right of the browser that would open a modal w/ seo analysis information. 

![artboard](https://cloud.githubusercontent.com/assets/3196536/17946143/10ed207a-6a15-11e6-9567-f11365372921.png)

SVG for button: https://cl.ly/032T1D2b380w

cc @kanaabe

**Comment by kanaabe** [comment]
thanks! cc @mdole
