### ISSUE TITLE
Strip html from copied text on image captions

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#799]
Steps to repro:
1. Copy caption text from http://expochicago.com/programs/expo-projects 
2. Add as caption to image in Writer
3. Save

Image caption doesn't get saved.

**Comment by eessex** [comment]
@kanaabe - though was able to reproduce this a few weeks ago, it seems to be working -- basic html, links, including all the captions from expo chicago are copying and pasting with no problem.
