### ISSUE TITLE
Find section by slug not working

### ISSUE THREAD

**Issue by starsirius** [artsy/positron#817]
We ran into an issue today where finding the [partner updates section](https://writer.artsy.net/api/sections/570293111b69841800bdb18b) by [slug](https://github.com/artsy/force/blob/ec0d73db4c78a99bb052bdee7f662a2425a72123/apps/rss/routes.coffee#L37) isn't working.

I am not exactly sure what has changed on the data side and we no longer have the `slug` field in the document. I fixed it temporarily by manually adding the field to the section in the Mongo db, but wonder what a real solution here is.

cc @kanaabe, @craigspaeth

**Comment by kanaabe** [comment]
@starsirius we should be using the Channel now instead! You can search by [slug](https://github.com/artsy/positron/blob/master/api/apps/channels/model.coffee#L44) too. When we updated artsy.net/artsy-partner-updates landing page, I "unpublished" the Artsy Partner Updates Section by removing the slug. I did this so mobile can fall back on the Force responsive view. Realizing now this wasn't the safest move. Did this affect the Artsy Partner Updates RSS feed?? Sorry I missed that one. Feel free to use the Channels instead. They mostly work the same.

**Comment by starsirius** [comment]
Oh I totally missed the new Channel thing. I will update the RSS feed to use that and PR tomorrow. Thanks for pointing that out!

**Comment by kanaabe** [comment]
@starsirius was this updated on your end? I'd like to remove the Partner Updates slug from the section if we can!

**Comment by starsirius** [comment]
@kanaabe Haven't had a chance to work on this given another more pressing project. Do you mind if I update Force to use Channel and give you a heads-up by end of this week? 🙇

**Comment by kanaabe** [comment]
@starsirius: Gotcha! I'll just go ahead and do it then and PR to you. Should be simple

**Comment by starsirius** [comment]
@kanaabe That would be awesome! Thanks!!
