### ISSUE TITLE
SEO Tool V2

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#835]
Moves the seo tool out of a modal and into a drawer that expands out of a banner under the nav. This banner should display only on the 'Content' and 'Display' panels. 

The error messages should be limited to : introductionKeyword, keywordDensity, metaDescriptionKeyword,  and titleKeyword

![screen shot 2016-11-08 at 4 54 22 pm](https://cloud.githubusercontent.com/assets/3196536/20118853/33c57dcc-a5d4-11e6-8a86-d8005813ba20.png)
![screen shot 2016-11-08 at 4 54 17 pm](https://cloud.githubusercontent.com/assets/3196536/20118858/3614dd16-a5d4-11e6-8b3b-3e750b07f093.png)
![screen shot 2016-11-08 at 4 55 16 pm](https://cloud.githubusercontent.com/assets/3196536/20118866/3a7839a2-a5d4-11e6-8c75-ec134640f93a.png)
![screen shot 2016-11-08 at 4 55 22 pm](https://cloud.githubusercontent.com/assets/3196536/20118871/3cd03e2a-a5d4-11e6-85c9-b34d6a0c3fda.png)

Sketch file here: https://cl.ly/3832110y3O3j

**Comment by kanaabe** [comment]
What should the resolved msg look like @owendodd? 

Somethin like this?
![image](https://cloud.githubusercontent.com/assets/2236794/21778805/e81f99aa-d672-11e6-860d-4b300edb10d3.png)
