### ISSUE TITLE
Display Panel

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#836]
Allows editors to customize headline, metadata and other info on a per channel basis. The previews to the right should update to show how the content will look in context (would be good to make sure that the sizes in the comps are giving an accurate picture during the QA process). 

The default state for this panel would be the first drop down expanded, and the channel drop downs below collapsed. 

Filling out info in the first one should auto populate the subsequent matching fields. 

![screen shot 2016-11-08 at 5 02 18 pm](https://cloud.githubusercontent.com/assets/3196536/20119099/289599a4-a5d5-11e6-9afa-b6258968e8ef.png)

Sketch file here: https://cl.ly/3832110y3O3j

**Comment by kanaabe** [comment]
@owendodd: do we want these counts to update as people type? 
![image](https://cloud.githubusercontent.com/assets/2236794/20728391/8457d62c-b64b-11e6-8b47-b0cc641476e1.png)

**Comment by owendodd** [comment]
Ah yeah, I never updated that number. Will figure out what number works
best once I'm back!

[A.]  Owen Dodd

       Designer

       Artsy <http://artsy.net/>

owen@artsy.net

+1 303 819 0844 <//+1%20303%20819%200844>
