### ISSUE TITLE
Zero-state FilterSearch

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#853]
When searching something, deleting the contents of the input should search for the default list query.

**Comment by eessex** [comment]
@kanaabe  -- I know you showed me this issue recently but I wasn't able to reproduce, I believe this was added when building the 'articles list'

![filterless-search](https://cloud.githubusercontent.com/assets/1497424/22948389/4f819402-f2cc-11e6-95ec-2c74fa5badeb.gif)
