### ISSUE TITLE
Smaller SVGs on sidebar

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#856]
On small screens, the profile icon gets hidden if you have access to queue. We should change to the same format maybe as CMS? 

On a 1250px screen:
![image](https://cloud.githubusercontent.com/assets/2236794/20990134/6d6e0660-bca5-11e6-8a05-48a7d6a834b1.png)

cc @owendodd

**Comment by owendodd** [comment]
Wonder if we could consolidate these more, could see us moving drafts/published to a tab system similar to what exists in the new Queue view.

**Comment by kanaabe** [comment]
Ah sure I'm for that. Also `Sections` should just be removed entirely.

**Comment by craigspaeth** [comment]
👍  to consolidating drafts/published, I had originally considered that in the beginning of Writer, but there wasn't enough functionality to warrant it.
