### ISSUE TITLE
Can't add section after callout

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#859]
The plus button doesn't pop up on hover at the bottom of a callout section @kanaabe

**Comment by eessex** [comment]
@halleyjohnson, it looks like the edit tool below the callout is explicitly disabled.  

I'm noticing that there are also some limitations on where callouts can be placed (only between two text blocks), guessing the edit tools are disabled to help preserve this rule.

**Comment by kanaabe** [comment]
@eessex yep, this was placed when we had callouts that were floated to the right. Now that they're stand-alone blocks we can remove those rules.
