### ISSUE TITLE
Artworks being lost after saving in a draft

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#860]

**Comment by halleyjohnson** [comment]
https://writer.artsy.net/articles/585838f7c7bfd80011339847/edit
this artwork was in there: https://www.artsy.net/artwork/faith-ringgold-change-3-faith-ringgolds-over-100-pound-weight-loss-performance-storyquilt

**Comment by halleyjohnson** [comment]
and I need to publish this one today, but there are links to the artworks that were in there multiple times and went missing multiple times: https://writer.artsy.net/articles/5851832e802d6d0011f0d726/edit

**Comment by halleyjohnson** [comment]
@kanaabe
