### ISSUE TITLE
Stop images from sizing above their width?

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#862]
I don't think there's a way currently to keep images from stretching beyond their actual size (I size something at 600px wide, for instance, and it blows up to 1100 or more when published.

Example, the first image in this article: https://www.artsy.net/article/artsy-editorial-do-artists-have-the-right-to-disown-their-work

Happy to talk out solutions to this in person!

**Comment by kanaabe** [comment]
I think we would want to exhibit some level of control over image sizes still, since this kind of change would change the way all images on site look. Would a good in-between be for images to have a max-text-body-width option? That's a 560px max-width. cc @owendodd

**Comment by halleyjohnson** [comment]
If that'd be like the option we have on artworks, I think that's a good solution, though I might suggest adding a third size option in between the two if possible (also think this could be nice for artworks). Though that further option would def need design input

**Comment by eessex** [comment]
Marking this closed -- Positron now has layout options for images:
- overflow_fillwidth: max-width 1100px, max-height 90vh
- column_width: max-width: 580px, max-height 90vh
