### ISSUE TITLE
Steps to reproduce hang from #861

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#873]
TBD
Poll localhost

````
while true
do
	curl http://localhost:3005/api/articles; sleep 1
done
````

**Comment by kanaabe** [comment]
I was able to get these three spikes to happen:
![image](https://cloud.githubusercontent.com/assets/2236794/21701755/8a280cf6-d375-11e6-95af-9143858f8dc0.png)

After a fresh restart, hit the API a bunch of times. Nothing happens and there are no memory spikes or slow requests. Then, hit the client. In all three spikes, requests failed after playing around with the client. In the first two, it happened on the first request to stagingwriter.artsy.net. Then a `MongoError` occurred which forced a restart. The third spike didn't have an Mongo Errors (perhaps connection to our API was already down so we didn't even get to Mongo tries) and I had to force a restart to clear again.
