### ISSUE TITLE
Find solution for Scribe/AMD

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#878]
Scribe uses AMD and doesn't add deamdify to their package.json locally. Browserify doesn't have an easy way of forcing a transform on a sub module. We've had issues with packages like Lokka and Yoast because of this.

Options:
1. Send PRs to all the Scribe repos to add `"browserify": { "transform": [ "deamdify" ] }`
2. Use [Draft.js](https://github.com/facebook/draft-js). It's well-maintained and since we're hopping on the FB bandwagon, it seems to fit. This might be a lot of work up front (ie creating [custom components](https://facebook.github.io/draft-js/docs/advanced-topics-block-components.html#content) for the custom scribe plugins we currently have) but probably worth it in the end.
3. Make Yoast and Lokka happy with deamdify

Related conversations:
https://github.com/guardian/scribe/pull/175#issuecomment-240230366
https://github.com/substack/node-browserify/issues/1127

**Comment by eessex** [comment]
[ ] get draft running in positron
[ ] caption input
[ ] textarea input

CAPTION 
[ ] Doesn't allow line breaks
[ ] Strips only not-allowed html on paste

TEXT EDITOR
[ ] Can accept custom link-type for Artist
[ ] Can accept custom link-type for TOC
[ ] Custom types are converted correctly
