### ISSUE TITLE
Channel header on articles list

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#906]
So we know what channel we're in!

**Comment by eessex** [comment]
@owendodd , where is a good place to put this?

![screen shot 2017-01-27 at 5 20 58 pm](https://cloud.githubusercontent.com/assets/1497424/22389877/f12737b4-e4b5-11e6-8986-933463f396d8.png)

**Comment by owendodd** [comment]
@eessex How about this?

Requires a slight reorganization on this page, But should work well across. 

![screen shot 2017-01-27 at 5 53 53 pm](https://cloud.githubusercontent.com/assets/3196536/22390546/ade8d6e8-e4b9-11e6-8609-d3dfa2901b28.png)
![screen shot 2017-01-27 at 5 53 59 pm](https://cloud.githubusercontent.com/assets/3196536/22390547/ade951ea-e4b9-11e6-980d-a85f3542638f.png)
![screen shot 2017-01-27 at 5 54 05 pm](https://cloud.githubusercontent.com/assets/3196536/22390548/ade9af50-e4b9-11e6-80f7-78bfc97498eb.png)

**Comment by eessex** [comment]
Cool!  Will get this going soon
