### ISSUE TITLE
Replace npm with Yarn

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#924]
It's faster, and more reliable than npm.

Deets here: https://github.com/yarnpkg/yarn

**Comment by eessex** [comment]
Attempted to switch to yarn but experienced some problems with installing dependencies, specifically bcrypt's bindings dependency.  This was a known issue in an earlier version of Yarn, supposedly closed, looks very similar to what is happening here: https://github.com/yarnpkg/yarn/issues/1848
