### ISSUE TITLE
App trying to GET /null

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#942]
Happens when you load the articles list. Not urgent, but unnecessary.

**Comment by kanaabe** [comment]
Reopening this because I'm still seeing /null fetches in my dev environment.

![image](https://cloud.githubusercontent.com/assets/2236794/26593363/c831c8e2-4531-11e7-95b8-37067530c184.png)

**Comment by kanaabe** [comment]
Fwiw, it seems to be happening when I switch tabs from the Published list to Drafts.

**Comment by eessex** [comment]
Thanks for catching- will check this out
