### ISSUE TITLE
Add custom key commands to text editor

### ISSUE THREAD

**Issue by eessex** [artsy/positron#971]
- [x] h2
- [x] h3
- [x] removeFormat
- [x] linkPrompt
- [x] unlink
- [x] insertOrderedList
- [x] insertUnorderedList

**Comment by eessex** [comment]
removeFormat is the same as unlink.

**Comment by kanaabe** [comment]
Is this closed then @eessex ? If so please feel free to close yourself.

**Comment by kanaabe** [comment]
Oh, didn't see your PR!
