### ISSUE TITLE
Missing window.global

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#987]
I'd like to see a little more detail on this weird thing we have to do on React components. Is there something cleaner/clearer we can do to ensure that global is present on these components?

**Comment by eessex** [comment]
Not sure why this would be affecting the list view, but the window.global must be declared in all files that require Draft. 

Currently that includes:
/client/apps/edit/components/section_text/index.coffee
/client/components/rich_text_caption/index.coffee
/client/components/rich_text/components/input_paragraph.coffee

As well as the corresponding tests to each.

**Comment by kanaabe** [comment]
Cool, thanks! I'm definitely confused by this still but if it happens on `ArticleList` maybe it's a React (since 15?) thing. Is there a Draft issue/doc that says you need the global?

**Comment by eessex** [comment]
Resolved in a newer version of draft
