### ISSUE TITLE
Disallow empty H2's?

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#990]
Should we allow these? I'm not sure if we had these before Draft.js but the weekly news email started looking like this which depends on H2s having content: 

![image](https://cloud.githubusercontent.com/assets/2236794/24315313/bc5306f2-10bc-11e7-9bc4-99c9853ca664.png)

the template looks for h2's and renders the more >> link if there is one. we should either disallow empty h2s or fix the template in ST to ignore them. Not sure which is better atm

**Comment by eessex** [comment]
Fixed on the sailthru side
