### ISSUE TITLE
Couple of weird things on gallery insights

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#994]
Weird line break / read dot on email sign up
![screen shot 2017-03-29 at 8 22 02 pm](https://cloud.githubusercontent.com/assets/3196536/24470008/b96481aa-14bd-11e7-9351-69313130bcb1.png)

Weirdness with share buttons
<img width="629" alt="screen shot 2017-03-29 at 8 23 56 pm" src="https://cloud.githubusercontent.com/assets/3196536/24470028/ca1dae5e-14bd-11e7-99d5-585fd7b26e76.png">

**Comment by kanaabe** [comment]
this should be moved to Force!

**Comment by owendodd** [comment]
WHOOPS!
