### ISSUE TITLE
Create a way to exclude some channels from sitemaps

### ISSUE THREAD

**Issue by dblock** [artsy/positron#995]
We have channels in production like `Kanaz Test Channel` which ends up being included in sitemaps.

Maybe channels could have a `public` flag or something like that, although that's starting to smell like gravity ;)

**Comment by eessex** [comment]
- [ ]  Writer: Add indexable field to articles api + user interface
- [ ]  Force: Add no-index meta tag to articles if indexable is false
- [ ]  Cinder: Exclude articles without indexable from sitemaps
